# Asymmetric information: "optional" for 2019-20


<aside class="notes">

*Note for 2019-20:* This material will be included in the final exam but only for parts B or C, where you may choose to address this material or an alternative question.

In this sense it is not *required* in your examination but it would be helpful and thus worth studying it, particular if you are interested in this.

</aside>

Also see separate notes on VLE


** Market failures: Asymmetric information** (Moral hazard, adverse selection, signaling)


Broadly, asymmetric information is a situation in which one party to a transaction has more information than the other party.


See separate notes on VLE; brief summary below


## Principal-Agent Problem

A principal “hires” an agent to perform some task, and the agent has private information, either about her actions or her type.

- Employer-employee relationship:

- Employer (principal); employee (agent)

- A worker has full information about whether she is working hard (action) or her job skills (type).

- How does an employer monitor/influence effort?  How does a potential employee signal their high-quality or low-quality type?

\

**Moral hazard** problem occurs when an agent’s action is private information

- Offering incentives may be costly (because of limited liability, risk aversion, and difficulties in writing contracts)

**Hidden information** ('privacy') problem occurs when an agent’s type is private information.

- 'Lemons problem' $\rightarrow$ potential **Adverse selection** and/or closing down of markets

- Principal/agent $\rightarrow$ 'distorted' output or quality for 'less favored' type to reduce 'information rent' for 'better' type

`r format_with_col("Also, if the Agent moves first (instead of the Principal), this can lead to a 'signaling game', which we will not cover here. See 'the signaling benefit of education.","gray")`


\

Automobile insurance

- When selling a policy the company does not know whether you are a high risk or low risk driver (adverse selection)

- Since you are insured you are less careful (moral hazard)

## Moral hazard: Basic principles

1. If 'effort' (or honesty) is unobserved or un-enforceable, principal (P) must offer incentives based on *observed performance* or *output* of the agent.

2. If output has (uncontrollable) *random component*, rewarding output shifts risk to the *agent* (A).

- If A is more risk-averse than P, if compensation must be tied to output $\rightarrow$ inefficient risk-bearing.

- Because of the cost of paying a 'risk premium' to A $\rightarrow$ P may demand less effort than is efficient

3. Otherwise, if P \& A have the same risk-attitude, P can 'sell the profits to A' $\rightarrow$ efficiency

- But not if A has 'limited liability' $\rightarrow$ inefficiency:
    - P can only 'reward' A not 'punish' her $\rightarrow$ costly $\rightarrow$ demand less effort

*See 'more formal moral hazard notes' (VLE) and Flowchart if interested*


## Lemons problem

*Where sellers know more about the value of used cars than buyers, some sales that would be mutually beneficial will not take place.*


Easiest model:

- Car quality $x$ distributed $x \sim U(0,1)$.

- Buyer values at $\frac{3}{2}x$, seller values it at $x$ (so efficiency requires trade!)

- Seller proposes 'tioli' price $p$


$\rightarrow$ Seller must choose $p \geq x$ $\rightarrow E(x|p)=\frac{1}{2}x$ $\rightarrow$ Buyer anticipates value $\frac{3}{2}\frac{1}{2}p=\frac{3}{4}p$

Buyer never accepts any price $\rightarrow$ market closes down


*See slightly more fleshed-out (VLE) if interested*


## To learn this material fully (and to be prepared to answer an exam question), please also read:

- ['Privacy'/Hidden Information](https://www.dropbox.com/s/mdit2mvjnln2bt2/beem101_adapt_hidden_info_slides_ho.pdf?dl=0) and suggested accompanying readings esp. from Laffont and Martimort.

- [Lemons/Adverse Selection](https://www.dropbox.com/s/wxymi69prteh3lb/notes_on_akerlof_09.pdf?dl=0)

You can also learn more about moral hazard [here](https://www.dropbox.com/s/qiraup69bcgum1m/1_MH1_2013_proofskim.pdf?dl=0) and more simply [here](https://www.dropbox.com/s/vvloducyvufdmlq/1e%20-%20easy%20Moral%20hazard%20background.pptx?dl=0) but it is unlikely to be on the final exam (for 2019-20)


