# Exams with answers and mock exams


<h4><span style="font-family: 'times new roman', times, serif;"><strong style="font-family: 'times new roman', times, serif; text-decoration-line: underline;"><span class="" style="font-family: &quot;Times New Roman&quot;, Times, serif;">Exams with answers, mock exams</span></strong></span></h4>
<p></p><ul><li><a href="https://www.dropbox.com/s/0mmd2cv5d9et1wf/mock_beem101_final_2020_no_ans.pdf?dl=0">2020 mock exam/rubric (no answers version (and sections B and C have 'hints of questions' only)&nbsp;</a></li><li><a href="https://www.dropbox.com/s/cwzqlem2eh2d2pg/mock_beem101_final_2020_w_ans.pdf?dl=0">2020 mock exam/rubric (with answers to section A, sections B/ and C have 'hints of questions' only)&nbsp;</a></li><li><a href="https://www.dropbox.com/s/qtyuy09nmo8v9kx/101midterm_2019_wans.pdf?dl=0">2019/20 midterm with suggested answers</a></li><li><a href="https://www.dropbox.com/s/mxxb955z2gvpb4i/mock-101midterm_2019.pdf?dl=0">2019/20 Mock midterm (no answers</a>)</li><li><a href="https://www.dropbox.com/s/sgiqk9njfhyz744/mock-101midterm_2019_wans.pdf?dl=0">2019/20 Mock midterm (with answers to MCQ and partial answers in part b --- will add more)</a></li></ul><p><br></p><p></p>
<p></p>
<p><span style="font-family: 'times new roman', times, serif;"><strong><span style="text-decoration: underline; font-size: small; font-family: Arial, Helvetica, sans-serif;" class="">Prior years' exams and mock exams with suggested answer guidelines</span></strong></span></p><p><u>Mid-term asessments and mock assessments</u></p><p><span style="font-family: 'times new roman', times, serif;"><span><span style="text-decoration: underline; font-size: small; font-family: Arial, Helvetica, sans-serif;" class=""></span></span></span></p><ul style=""><li style=""><span style=""><a href="https://www.dropbox.com/s/4zmnrhwpv5js3pw/MOCK_101midterm_2018-19_noans.pdf?dl=0" style=""><span style="">2018/19 Mock midterm (no answers)</span></a></span></li><li style=""><span style=""><a href="https://www.dropbox.com/s/9c9gd3vaytdamqp/beem101_2019_mockexam_andpractice_WIP_wans.pdf?dl=0" style="">2019 Mock final,&nbsp;with answers/guidelines</a></span></li></ul><p></p>
<ul>
<li><span style="font-size: small; font-family: 'times new roman', times, serif;"><span><span><a href="https://www.dropbox.com/s/h42z9inaupnhh5s/101midterm_2018-19_wans%202.pdf?dl=0">2018/19 Midterm with suggested answer guidelines</a>&nbsp;(added 8 Oct 2019)</span></span></span></li><li><a href="https://www.dropbox.com/s/5meen2m4z700sn1/101midterm2017-18.pdf?dl=0" style="font-family: &quot;times new roman&quot;, times, serif; font-size: small;"><span>Midterm with&nbsp; suggested answers 2017-18</span></a></li><li><a href="https://www.dropbox.com/s/wkyj3tbnq8dgq03/101midterm2016-17_extendedans.pdf?dl=0">Midterm 2016-17 with suggested answers&nbsp;<br></a></li></ul><p><u>Final assessments</u></p><ul><li><span style="font-size: small; font-family: 'times new roman', times, serif;"><a href="https://www.dropbox.com/s/uygcmk0kwsi210h/beem101final_2019_postexam.pdf?dl=0">2018 final exam with suggested answer guidelines</a></span></li><li><span style="font-size: small; font-family: 'times new roman', times, serif;"><span class="" style="font-family: Arial, Helvetica, sans-serif; font-size: small;"><a href="https://www.dropbox.com/s/y5uk15guqxa5wvf/beem101final_2018_postexternal_wans.pdf?dl=0">2017-18 final exam with suggested answer guidelines</a></span></span></li>
<li><span style="font-family: 'times new roman', times, serif;"><span style="font-size: small;"><a href="https://vle.exeter.ac.uk/pluginfile.php/1027741/mod_resource/content/1/2017finalexam.pdf"><span class="" style="font-family: Arial, Helvetica, sans-serif; font-size: small;">2016-17 final </span></a></span><span style="font-size: small;"><a href="https://vle.exeter.ac.uk/pluginfile.php/1027741/mod_resource/content/1/2017finalexam.pdf"><span class="" style="font-family: Arial, Helvetica, sans-serif; font-size: small;">exam with suggested answer guidelines</span></a></span></span></li>
<li><span style="font-family: 'times new roman', times, serif; font-size: small;"><a href="https://vle.exeter.ac.uk/pluginfile.php/1027741/mod_resource/content/1/2017finalexam.pdf"></a><b><span class="" style="font-family: Arial, Helvetica, sans-serif; font-size: small;">&nbsp;</span></b><span class="" style="font-family: Arial, Helvetica, sans-serif; font-size: small;">2017-</span><a href="http://vle.exeter.ac.uk/%20https:/www.dropbox.com/s/8a2id8kximknai2/beem101final_2018_MOCK.pdf?dl=0"><span class="" style="font-family: Arial, Helvetica, sans-serif; font-size: small;">2018 mock final exam; no answers</span></a></span></li>
<li><span style="font-family: 'times new roman', times, serif; font-size: small;"><a href="http://vle.exeter.ac.uk/%20https:/www.dropbox.com/s/8a2id8kximknai2/beem101final_2018_MOCK.pdf?dl=0"></a><span class="" style="font-family: Arial, Helvetica, sans-serif; font-size: small;">&nbsp;2017-</span><span class="" style="font-family: Arial, Helvetica, sans-serif; font-size: small;"><a href="https://www.dropbox.com/s/mu0jzb93j8b81cw/beem101final_2018_MOCK_wans.pdf?dl=0">2018 mock exam with suggested answers here&nbsp;</a></span></span></li>
</ul>
