# Notes to students {#note}

**Notes by instructor [David Reinstein](davidreinstein.wordpress.com/)**

## Level of this module

This module will not fully prepare you for doctoral study and academic research that requires advanced Microeconomics. That approach is taken in our MRes module, not in this module.   (Note that exams from year before 2016 are not indicative of what you will face in this module.)  This is required because of the diverse education backgrounds of the students in our programme. However, I will be including some more rigorous material, as well as state-of-the-art research, and I will give you pointers on pursuing more advanced extensions to the material.

## Readings and resources

This module will use a variety of resources: I will guide you through this via the 'handout' (really a partial online text) file. This draws heavily from several texts and other resources, including:

- Introduction to Economic Analysis version 2.1 by McAfee, Lewis, and Dale  -- available for free [LINKED HERE](https://www.scholars.northwestern.edu/en/publications/introduction-to-economic-analysis-v21)  under a Creative Commons license.

- Intermediate Microeconomics and its Application (an Undergraduate text) by Nicholson and Snyder (available at the bookstore for about £50... older editions are fine too)
    - A free alternative, at a similar level: [Microeconomics an Open Text by Douglas Curtis and Ian Irvine](https://open.umn.edu/opentextbooks/textbooks/microeconomics-markets-methods-and-models)

-  Microeconomics by Hugh Gravelle and Ray Rees (version 3, widely available online for free)
  - A somewhat more advanced-intermediate-level text which I think you will find very useful; this is not yet officially Open-Source, but you can find it online for free (and the authors are OK with this, I have emailed them). Just do a web search for 'Gravelle and Rees Microeconomics' and you will find the pdf

From time to time I will refer you (and draw from) another open source work that has *very clear explanations*:

-  [Quantum Microeconomics
with Calculus](http://www.smallparty.org/yoram/quantum/quantumcalc.pdf) by Yoram Baumann, the self-proclaimed 'World's First Standup Economist'

More rigorous, advanced and applied work will draw from

- David Autor’s MIT Open Courseware “Microeconomic Theory and Public Policy”; [all the files for this course can be downloaded here)[https://ocw.mit.edu/courses/economics/14-03-microeconomic-theory-and-public-policy-fall-2016/lecture-notes/] this will give you a flavor of the PhD level micro
- David Autor. 14.03 Microeconomic Theory and Public Policy. Fall 2016. Massachusetts Institute of Technology: MIT OpenCourseWare, https://ocw.mit.edu. License: Creative Commons BY-NC-SA.

- Academic articles and working papers as well as  some of my own writings... these are mentioned below


*A more detailed description of the texts is given [in the next section, here](#texts)


## This 'handout'/ web-book/ online resource

**Welcome to the exciting world of Microeconomics**

I wrote these notes to outline all of the material you are responsible for,  and to give you more resources and insight than I can convey in the short  amount of time we have during lecture.   I *don't* mean you're simply responsible for material in these printed notes:  I mean that these notes will aim to *refer to* everything that you are responsible for.

These notes are meant to be a complement to the textbooks and readings (and to the lectures,  tutorials/problem sets and other material on the ELE) and to tie all of this together.

<!-- I am providing you these notes both as a complete file as well as divided by lecture week (approximately). Use either version.
-->

 I will try my best to stick to the structure outlined in these notes.  However,  each year the module adjust slightly as we go and I will need to make updates to these notes as we go along.  I will try to keep you informed of any changes via the VLE forums.

<br> \bigskip

*Notes versus slides?:*

These notes should include all of the slide material *plus* explanatory notes and enrichment material. (However, I left out some of the jokes.) I use some abbreviations before certain notes to help you understand how to digest this.  I will also try to make the slides themselves available after the lectures,  even though they are redundant– these notes have everything.

<br> \bigskip


*Some 'markers' and abbreviations:*

- 'McDL' refers to the [McAfee, Dale and Lewis text](https://www.scholars.northwestern.edu/en/publications/introduction-to-economic-analysis-v2)

- 'NS'  refers to the Nicholson and Snyder text (usually chapters/numbering from the 12th edition is referenced;  if you're using an earlier edition, make sure the content corresponds)

- GR refers to Gravelle and Rees' Microeconomics text (free online, more or less)

- 'DA' refers to [David Autor's MIT open courseware notes for Microeconomic Theory and Public Policy](https://ocw.mit.edu/courses/economics/14-03-microeconomic-theory-and-public-policy-fall-2016/lecture-notes/)

- 'QMC' refers to ['Quantum Microeconomics with Calculus'](http://www.smallparty.org/yoram/quantum/quantumcalc.pdf)  (Baumann)


<!--
- 'LC' indicates a lecturer comment I may make in lecture that you don't need to worry about (I meant to cut these but I sometimes forget to)
-->

`r format_with_col("Text in blue usually refers to questions you should  try to answer on your own (and I sometimes provide suggested answers in the footnotes. Try to answer it yourself first.)","blue")`

`r format_with_col("Some text is given in gray to indicate that this is a side point or a discussion. (I'm moving most of this to footnotes.)","gray")`


- 'Comprehension Q:' A question you should be able to answer if you are following along.

- 'T numbers' (take these loosely please) refer to the weeks of term in which I  intended to cover specific material.
    - For example 'T1:03 - T1:04a' means 'term 2 week three (both lectures) and term 2 week 4, first lecture only'


<!---
batch file: 'bash \$HOME/"Google Drive/exeter_teaching/be2024/compileslidesnotes.sh"'
-->

<br> \bigskip

### Tech details of this book ('do I call this 'collophon'?)

I created this in Rmd (the 'R languages' 'markdown'), including some latex and html code too. 

This is all put together by  Knitr and Bookdown using the 'Pandoc' conversion tool into an Html file which I'm hosting via Github pages for now. 

I'll occasionally use/show some R code; you should consider getting proficient in R and developing other 'data-sciencey' tech skills (things like R, Python, Stata, git, vim, shell scripts...)

Let me know if you want to look 'under the hood'. 

## Outline and description of module {#outline}

**Planned syllabus, coverage:**

*The planned module outline is below;  as noted, timings may need to be adjusted,  and so material may cut for time constraints.  Feel free to skip over the first time you read these notes; you may want to refer to this later. The relevant part of this outline will be repeated at the beginning of each 'section.'*

- **Module outline, background, Economic models (and maths tools), 'empirical' evidence** (\*) [1a] [First lecture](intro-lecture)
    - McAfee et al ('McDL'), Chapter 1
    - (or) Nicholson \& Snyder (NS): Chapter 1 and 1a
    - Discussion of 'empirical identification': [The mixtape, Scott Cunningham](http://scunning.com/cunningham_mixtape.pdf) pp 18-22
    - Math revision concepts in
        - [DA lecture 3](https://ocw.mit.edu/courses/economics/14-03-microeconomic-theory-and-public-policy-fall-2016/lecture-notes/MIT14_03F16_lec3MathTools.pdf); we may not use all of this
        - QMC 1.3 (some good studd don't worry too much about derivative rules)
        - NS ch 1a (you need this and a bit more)
    - T1:01a (Term 1, week 1, first hour; 'empirical')

<!--  `r format_with_col("First problem set: Mathematical approaches, economic models, revision and warm-up; (to add: some practice MCQ's)","blue")`
I will put up slides and other resources to help you with this (and we will re-cover some of this when we apply it throughout the module). The maths you need will also be simultaneously covered in your Optimisation and Econometric modules.
-->

- Supplementary reading:
    - Friedman, Milton. "The methodology of positive economics." (1953): 259. *Classic but perhaps outdated*
    - Sugden, Robert. "Credible worlds: the status of theoretical models in economics." Journal of Economic Methodology 7.1 (2000): 1-31.
    - Loomes, Graham, Chris Starmer, and Robert Sugden. "Observing violations of
    - Choi, Syngjoo, et al. "Who is (more) rational?." The American Economic Review 104.6 (2014): 1518-1550.


- **[Utility and choice](util-choice)** (Utility, preferences, indifference curves, budget constraints ...) [1b-2]
    - McDL: Ch 12, plus 'preference relations', Ch 20: Math: Deriving supply and
demand curves (demand part), esp 20.3
    - AUT: [Lecture 3 - Axioms of Consumer Preference and the Theory of
Choice](https://ocw.mit.edu/courses/economics/14-03-microeconomic-theory-and-public-policy-fall-2016/lecture-notes/MIT14_03F16_lec3.pdf) (note, slightly different notation)
    - NS: Ch 2
    - **T1:01b, 2**
    - `r format_with_col("Second problem set (NS chapter 2): Preferences, Utility, Consumer optimization (individual and market demand curves), and MCQ's for revision","blue")`

- Supplementary reading:
    - Waldfogel, Joel. "The deadweight loss of Christmas." The American Economic Review 83.5 (1993): 1328-1336.
    - Reinstein, David. "The Economics of the Gift." (2014).
    - D. Colander \\Edgeworth's Hedonimeter and the Quest to Measure Utility'' Journal of Economic Perspectives, Spring 2007: 215-225.

***

-  **Demand curves** (individual and market, and properties of each) (\*) [3-4]
    - NS: Ch 3
    - DA: [Lecture Note 6 – Demand Functions: Income Effects, Substitution Effects, and Labor Supply](https://ocw.mit.edu/courses/economics/14-03-microeconomic-theory-and-public-policy-fall-2016/lecture-notes/MIT14_03F16_lec6.pdf), esp. sections 1-3
    - McDL: 2.1, 2.3, 3.1 (elasticity), parts of Ch 12
    - QMC: Chapter 17 (elasticities -- very clear treatment, Chapter 18 (supply and demand details)
    - T1:3-4

    - `r format_with_col("Second problem set, second part: Preferences, Utility, Consumer optimization, individual and market demand curves","blue")`


- **Production, costs**  (Production functions, isoquants, RTS, scale, types, choice of inputs, LR and SR) (\*) [5]
    - McDL: Ch 9, 'Producer theory - costs' (parts, esp. 'Production Functions'), Ch 10 'Producer theory - dynamics' (parts, esp. 'Economies of Scale and Scope')
    - NS: Ch 6-7 (parts)
    - QMC: Ch 20 (supply part)
    - T1:04

- Supplementary reading:
    - Garber, Alan M., and Jonathan Skinner. "Is American health care uniquely inefficient?." The Journal of Economic Perspectives 22.4 (2008): 27-50.

- **Profit maximisation and supply, Perfect competition in a single market** (Firms, MR=MC, shut-down, (Brief: Supply curve, entry/exit, CS and PS, tax incidence)) (\*) [5b-6]
    - NS: Ch 8-9
    - McDL: - Ch 10 'Producer theory - dynamics' (parts, esp 'Reactions of Competitive Firms', 'Dynamics with constant costs', 'General Long-Run Dynamics')
    - T1:5-6a (continued)

- Supplementary reading:
    - Gibbons, Robert. "Four formal (izable) theories of the firm?." Journal of Economic Behavior & Organization 58.2 (2005): 200-245.

- ** General equilibrium and welfare (brief)** (interrelated markets and equilibrium prices, efficiency of perfect competition, failures) [6b]
    - Main resource: this handout
    - NS: Ch 10 (parts)
    - DA: [Lecture 10 General equilibrium in a pure exchange economy](https://ocw.mit.edu/courses/economics/14-03-microeconomic-theory-and-public-policy-fall-2016/lecture-notes/MIT14_03F16_lec10.pdf)
    - McDL: Ch 14 (parts)
    - QMC: Ch 21; 'Transition: Welfare Economics' ... an interesting narrative
- `r format_with_col("Third problem set: Costs/production, perfect competition in a single market, Welfare/General Equilibrium ","blue")`

- Supplementary reading:
    - Slonim, Robert, Carmen Wang, and Ellen Garbarino. "The market for blood." The Journal of Economic Perspectives 28.2 (2014): 177-196.


***

<!---
 **WILL SKIP: Market failures: Asymmetric information** (Moral hazard, adverse selection, signaling)
-->

- **Market failures: Public goods** (attributes, equilibrium underprovision, remedies) [6b-7a]
    - McDL: Ch 8 -- public goods
    - NS: Ch 16 -- public goods section only, possible supplements on voluntary provision of PG/charity
    - T1:06b-7a
    - `r format_with_col("Fourth problem set: Public goods ","blue")`

- Possible supplementary reading (these will be updated):

Chaudhuri, 2009. Sustaining cooperation in laboratory public goods experiments: a selective survey of the literature

Ledyard, J.O., 1993. Public Goods: A Survey of Experimental Research, Division of the Humanities and Social Sciences, California Institute of Technology.

Vesterlund, Lise. "Voluntary giving to public goods: moving beyond the linear VCM." Handbook of Experimental Economics 2 (2012).

Vesterlund, Lise. "Using Experimental Methods to Understand Why and How We Give to Charity." The Handbook of Experimental Economics (2013).

Varian, Hal R. "Buying, sharing and renting information goods." The Journal of Industrial Economics 48.4 (2000): 473-488.

- **Monopolies, pricing and price discrimination** (single firm with market power; leads to another market failure) [7b-8a]
    - McDL: Ch 15 -- Monopoly
    - NS: 11.2-11.4
    - QMC: Appendix A.1 - Monopoly - the vanilla version
    - T1:07b-8a
    - Article: [Should we help companies tailor prices to your wage packet?](https://theconversation.com/should-we-help-companies-tailor-prices-to-your-wage-packet-47719)
    - With accompanying [worked examples](https://docs.google.com/document/d/16jos_PT9w1wGpyD5A8ZiWJ9HW6kaLOJH6EWc_AYWnkk/pub)
    - More advanced: 'The Government May Want to Encourage Price Discrimination by Income' [Linked here](https://davidreinstein.wordpress.com/research-and-publications/)

- `r format_with_col("Fifth problem set: Monopolies and price discrimination","blue")`

<!--
- ** Imperfect competition (brief) ** (multiple firms with market power; esp Bertrand/Cournot models)
-->

***

- **Uncertainty** (basic concepts, EU, risk aversion, investment choices) [8b,9a]
    - DA: [Lecture Note 16: Uncertainty, Risk Preference, and Expected Utility Theory](https://ocw.mit.edu/courses/economics/14-03-microeconomic-theory-and-public-policy-fall-2016/lecture-notes/MIT14_03F16_lec16.pdf)
    - NS: Ch 4 (not including 4a)
    - McDL: Ch 13, section 4 'Risk Aversion'
    - QMC: Ch 5 (does not use utility functions, but good discussion of diversification)
    - T1:08b-9a

    - `r format_with_col("Sixth problem set: Uncertainty (Chapter 4)","blue")`

- Supplementary reading:
  - Holt, C., and S. Laury (2002), Risk Aversion and Incentive Effects, American Economic Review, v. 92 (5): 1644-1655.

- For a popular audience: Reinstein (2016) 'Should you hedge your bets on a Brexit?' [LINK](https://davidreinstein.wordpress.com/2016/06/19/should-you-hedge-your-bets-on-a-brexit/)

- **Game theory (and lab experiments)** (*Strategic* interaction) [9b,10]
    - QMC: Ch 9, 10, 12 (includes 'iterated dominance')
    - McDL: Ch 16
    - NS: Ch 5 (parts)
    - Several additional concepts from handout, plus supplement on experiments
    - T1:09b-10

-  `r format_with_col("Seventh problem set: Game theory (chapter 5, plus a few additional concepts covered in lecture)","blue")`



- Supplementary reading:
    - Spence, M. (1973): 'Job market signaling,'? The Quarterly Journal of Economics, vol. 87, pp. 355-374.
    - 'Ten Little Treasures of Game Theory and Ten Intuitive Contradictions' Goeree and Holt, 2001

- **Asymmetric information** (Moral hazard, adverse selection, signaling)
  - Separate notes/handouts, to be integrated in
  - Readings tbd

- **Behavioural economics** -- first lecture (limits to cognition, willpower, self-interest), second lecture (applications) [11]
    - NS: Ch 17, plus supplements
    - T1:11
    - Further readings tbd
    - `r format_with_col("Eighth problem set: Behavioural economics","blue")`


Overall each reading is optional, but to do well on the exam you need to do at least some of these readings, and/or cover some of the more advanced material.


- Supplementary reading: theory
    - Amos Tversky & Daniel Kahneman, 1979. "Prospect Theory: An Analysis of Decision under Risk" (*Seminal*)

- Supplementary reading: applications and empirical work
    - DellaVigna, Stefano. "Psychology and economics: Evidence from the field." Journal of Economic literature 47.2 (2009): 315-372.
    - Benartzi, S. & Thaler, R.H., 2007. Heuristics and biases in retirement savings behavior. The journal of economic perspectives, pp.81-104.
    - Farber, H., 2008. Reference-dependent preferences and labor supply: The case of New York City taxi drivers. The American Economic Review. Available at: http://www.ingentaconnect.com/content/aea/aer/2008/00000098/00000003/art00021 [Accessed November 19, 2015].
    - (Behavioural insights team) EAST: Four simple ways to apply behavioural insight
    - Kellner, Reinstein and Riener, 2016. [Conditional generosity and uncertain income: Field and lab evidence](https://dl.dropboxusercontent.com/u/91553/Giving_and_Probability.pdf)
    - Material linked at [giveifyouwin.org](giveifyouwin.org)

***

- **Revision lecture, catch-up**
    - T1:12a




