# Supplement:  Gift-giving (Christmas, Chuseok, birthdays...): why do people do it and is it efficient?

## Introduction

Enrichment (optional):

Waldfogel (1993), “The Deadweight Loss of Christmas”; Response papers … esp [REINSTEIN](http://repository.essex.ac.uk/10009/1/dp749.pdf)

The Tuesday Podcast: Making Christmas More Joyful, And More Efficient

\

## Does Christmas gift-giving reduce welfare?


- Waldfolgel (1993), "The deadweight loss of Christmas."


Waldfogel's basic argument:

- Gift-givers will not know the recipients exact preferences, and will typically buy gifts the recipient would not themselves have purchased. This implies recipients have other items they would gain more for utility from at the same cost.

- Giving a cash gift would thus allow them to better optimize, thus put them on a higher indifference curve (higher utility).

- He depicts an indifference curve between a 'gift good' and 'other goods' and compares this to a rotation in the budget constraint to a shift outwards.

\

Waldfogel collected evidence from surveying university students, asking them to estimate/state

- the prices paid for the gifts they received
- How much they would have been willing to pay for these
- (alternately) how much they would need to be paid to part with these
- who gave the gifts

He claimed that his evidence demonstrates that students stated a significantly lower value (WTP and WTA) then the gifts were worth (87\% on average), and this gap was larger the less 'close' the giver was to the recipient'.

\


He argues this demonstrates a deadweight loss.


\


`r format_with_col("Are there flaws in his argument and his evidence?","blue")`

- Could gift-giving instead *increase* welfare?

\

Others have questioned Walfogel's empirical findings, (Solnick – Hemenway 1996; List – Shogren 1998.) instead finding a gain in value over the cost of the gifts. (Reinstein, 'The Economics of the Gift', 2014)

**Empirical critiques**

<br> \bigskip

- Solnick and Hemenway highlight the non-representativeness of W's survey, and potential experimenter demand and framing issues -- these were Yale microeconomics students. They re-run a similar survey on a (claimed) more representative sample and find a very large gain in value relative to cost (value of 214\% of cost).

- The List and Shogren (1998) paper's main critique is that the Waldfogel's WTP/WTA estimates are based on a hypothetical non-incentivised survey. They ran there own surveys about material and sentimental value, and then a hypothetical and a real incentive compatible (random n'th price) auction. Putting this together they estimate a 121-135\% \textit{gain} in value relative to the cost of the gifts.

(There are other empirical papers that could also be cited)

\

**Alternate models**

The standard explanation for this is that gifts gain a sentimental or symbolic value. Other gains may accrue to the giver, such as the shared consumption benefits [the giver also enjoys the use of the gift, or the act of giving] and signaling benefits, or the ability to signal one’s understanding of the receiver’s tastes and needs.

- Gift-giving allows the giver to accumulate goods that cannot be purchased commercially;
- When the giver retains some use, experience, or control over the gift, she shares in the consumption of it; (and this may help solve a public goods problem)
- Considering behavioural issues such as regret aversion, gift-giving may offer overlooked efficiencies that may balance out the deadweight losses from ‘inadequate gifts’;

(From Reinstein, 'The Economics of the Gift', 2014)

\

- Also, repeated bilateral gift-giving may be a way to demonstrate and sustain trust \dots
    - Buying 'rounds' in the pub

<!--
Add picture here of rounds in the pub
-->

- It can also be a way to demonstrate one's understand of the others' preferences, which itself may be of value
- a repeated 'gift economy' can substitute for market exchange in environments where trust is critical
    - Some historians have argued that a 'gift economy' evolved into the market economy




