---
title: "Beem101 4th week lecture"
output:
  pdf_document: default
  html_document: default
---

**Overall goal: Finish demand, begin production side**

# Demand coverage

## 'Fancy/advanced stuff'

- Income elasticity

- Engel aggregation

- Expenditure and indirect utility functions


## Applications: Back to simpler material

- Bias of CPI based on a fixed basket

- Tax incidence, burden of a commodity tax, reference powerpoint

- Inefficiency of subsidies/gifts (see powerpoint)
  - Motivate discussion of gift-giving literature 
  
*Break?*  

## More demand (overall stuff)
  
- Brief on cross-price elasticities (read at home), mention Slutsky matrix

- Consumer surplus (simple depiction, mention more formal concepts)

- Market demand and aggregating demand (brief, read at home)

- Elasticities
  - Price elasticity of demand: Relevance for impact of price change on revenue (mention proof of this in web-book)
  - Other elasticities (read at home)
  
## Introduction to production side
  



