# Notes to students; overview {#note}

**Notes by instructor [David Reinstein](davidreinstein.wordpress.com/)**


## Focus and style of this module


**This is...**

1. a **Microeconomics** module.  We will learn and use maths and rigorous logic to consider deep questions of:

- Individual preferences, choices and optimization subject to constraints

- How individuals interact with one another, and the consequences of this (Game theory and mechanism design/agency problems)

- "Markets", prices, and "welfare" (how much value is created, who gets what, how do we consider these outcomes as a society)

- Psychological influences on the above, and limits to optimization (Behavioral Economics)

\


2. a  **Selective and bespoke** module

We will not cover 'all of Microeconomics'.  I will **focus on a limited set of concepts, models and application**s (and academic articles) that I hope you will find most interesting and useful.

We will skip many major important topics. But that's OK. We will learn tools, 'modes of thinking', and 'modes of proving results' that should strengthen your brain muscles and help you understand a much wider body of material.

- I often focus on models with 'surprising' or 'counter-intuitive' results. If you can explain the logic behind these (as well as the maths), you have achieved an understanding beyond a layman's intuition.

- I will try to incorporate a small set *applications* that are particularly relevant to your careers and your research interests.
,
<div class="marginnote">
I may also try to incorporate data, statistics/empirical modeling, and 'computer coding' because these will be super-important in your career.
</div>

*Please give me feedback on what you are interested in.*


3. an **Inquisitive module**: we ask **the 'how?', 'why?', 'so what?', and 'is this reasonable?'** ... of the models and concepts

When studying Economics, I often models presented, with strong assumptions, without any explanation of what these were for and how they could be justified. In this module we will always be skeptical and carefully ask 'what is the purpose' of each model and concept.

<div class="marginnote">
For example, 'what does it mean to say that something is a mixed-strategy Nash equilibrium?' ... Do we expect people to actually randomise in this way?
</div>



## Level of this module

This module is adapted to students from a variety of backgrounds.


For students interested in pursuing a PhD in Economics, and interested in research:

- We will cover some approaches and relevant building blocks, and I will point you to relevant materials for further enrichment

- I will incorporate content from academic literature ('articles in peer reviewed journals') and sophisticated research considerations

- I will incorporate my own research, research methods, and 'really getting our hands dirty' in digging into research questions, building theoretical (maths) models, and even perhaps experiments, coding, and data analysis

- We will discuss *your* proposed research, relate microeconomic theory and models to this, and bring this into coursework


*However, please note that will not fully prepare you for doctoral study and academic research that requires advanced Microeconomics. MRes programmes and modules are better geared to this.*


\

For students coming from backgrounds with limited Economics training and limited abstract maths:

- I will explain most concepts 'from the ground up', or point you to what you will need to revise.

- I will present most material *also* at an intermediate level, using diagrams and simple intuition.

<div class="marginnote">
But note that you need to have SOME background in Economics to do well in this module. This is an MSc-level Economics module, after all.
</div>


\

For students who are not as fluent in English as they would like to be (perhaps many/most of our students):

- I will try to communicate clearly and at a reasonable pace, avoiding slang and using diagrams and maths to convey ideas
- Most of what I say in lectures/videos/tutorials is also in writing here in this web book (or in links)
- I will strongly encourage you to participate actively and try to help you improve your English communication skills.




## Readings and resources

This module will use a variety of resources: I will guide you through this via this online text. **Consider this online text the 'governing resource'.**

This draws heavily from several texts and other resources, **all of which are free and available online**. I will make it clear what come from where, and where you can find additional readings.

In particular:

1. "O-R": [Models in Microeconomic Theory, by Osborne and Rubinstein](https://www.openbookpublishers.com/product/1171)


> Our main aim is to give the reader an understanding of the concepts of model and equilibrium in microeconomic theory

This book is very precise, abstract (in a mathematical sense), and extremely well-written and full of wisdom and insight. It is *dense*; don't worry if it takes you a long time to digest each concept (but if you get stuck, please do ask questions and try different approaches).  It is the most relevant (at least of these three) for further postgraduate/PhD study.

The authors claim 'the mathematics we use is elementary'. However, I think it contains a deep sort of maths that you will find challenging. As they say, 'many of the proofs involve sustained logical arguments'.



2. [Quantum Microeconomics with Calculus](http://www.smallparty.org/yoram/quantum/quantumcalc.pdf) by Yoram Baumann, the self-proclaimed 'World's First Standup Economist'

This is somewhat less rigorous than O-R, but it has its own strengths. It approaches the material in an unusual way, and covers some material that is non traditionally covered in Economics courses (and skips many core concepts).

3. [Introduction to Economic Analysis version 2.1 by McAfee, Lewis, and Dale]](https://www.scholars.northwestern.edu/en/publications/introduction-to-economic-analysis-v21)

This is a more traditional text, with more 'computational-style' problems. It covers a wider set of Economics concepts than the others.


\

### Other relevant resources

**Simpler resources**

- Intermediate Microeconomics and its Application (an Undergraduate text) by Nicholson and Snyder (available at the bookstore for about £50... older editions are fine too, but beware of some changes). We have used this for this module in past years.
    - A free alternative, at a similar level: [Microeconomics an Open Text by Douglas Curtis and Ian Irvine](https://open.umn.edu/opentextbooks/textbooks/microeconomics-markets-methods-and-models)

-  Microeconomics by Hugh Gravelle and Ray Rees (version 3, widely available online for free):  A somewhat more advanced-intermediate-level text which I think you will find very useful; this is not yet officially Open-Source, but you can find it online for free (and the authors are OK with this, I have emailed them). Just do a web search for 'Gravelle and Rees Microeconomics' and you will find the pdf


\

**More rigorous, advanced and applied work will draw from**

- David Autor’s MIT Open Courseware “Microeconomic Theory and Public Policy”; [all the files for this course can be downloaded here)[https://ocw.mit.edu/courses/economics/14-03-microeconomic-theory-and-public-policy-fall-2016/lecture-notes/] this will give you a flavor of the PhD level micro
- David Autor. 14.03 Microeconomic Theory and Public Policy. Fall 2016. Massachusetts Institute of Technology: MIT OpenCourseWare, https://ocw.mit.edu. License: Creative Commons BY-NC-SA.


**Also**

For maths, see also [Mathematical methods for economic theory](https://mjo.osborne.economics.utoronto.ca/index.php/tutorial/index/1/toc) ... also free online!

\


- Academic articles and working papers as well as  some of my own writings... these are mentioned below




## This web-book: the Governing Resource

**Welcome to the exciting world of Microeconomics**

I wrote these notes to outline all of the material you are responsible for,  and to give you more resources and insight than I can convey in the short  amount contact time that we have.   I *don't* mean you're simply responsible for material in these printed notes:  I mean that these notes will aim to *refer to* everything that you are responsible for.

These notes are meant to be a complement to the texts and readings (and to the lectures/videos,  tutorials/problem sets and other material on the ELE) and to tie all of this together.

<!-- I am providing you these notes both as a complete file as well as divided by lecture week (approximately). Use either version.
-->

 I will try my best to stick to the structure outlined in these notes.  However, things may adjust slightly as we go and I will need to make updates to these notes as we go along.  I will try to keep you informed of any changes via the VLE forums.

<br> \bigskip

*Notes versus slides?:*

These notes should include all of the slide material *plus* explanatory notes and enrichment material. (However, I left out some of the jokes.) I use some abbreviations before certain notes to help you understand how to digest this.  I will also  make the slides themselves available even though they are redundant– these notes have everything.

<br> \bigskip


### 'Markers', abbreviations, and callouts/boxes {#markers}

- OR:  Osborne and Rubinstein's [Models in Microeconomic Theory]((https://www.openbookpublishers.com/product/1171)


- 'McDL' refers to the [McAfee, Dale and Lewis text](https://www.scholars.northwestern.edu/en/publications/introduction-to-economic-analysis-v2)

- 'QMC' refers to ['Quantum Microeconomics with Calculus'](http://www.smallparty.org/yoram/quantum/quantumcalc.pdf)  (Baumann)

- 'NS'  refers to the Nicholson and Snyder text (usually chapters/numbering from the 12th edition is referenced;  if you're using an earlier edition, make sure the content corresponds)

- GR refers to Gravelle and Rees' Microeconomics text
- 'DA' refers to [David Autor's MIT open courseware notes for Microeconomic Theory and Public Policy](https://ocw.mit.edu/courses/economics/14-03-microeconomic-theory-and-public-policy-fall-2016/lecture-notes/)



<!--
- 'LC' indicates a lecturer comment I may make in lecture that you don't need to worry about (I meant to cut these but I sometimes forget to)
-->

`r format_with_col("Text in blue usually refers to questions you should  try to answer on your own (and I sometimes provide suggested answers in the footnotes. Try to answer it yourself first.)","blue")`

`r format_with_col("Some text is given in gray to indicate that this is a side point or a discussion. (I'm moving most of this to footnotes.)","gray")`


- 'Comprehension Q:' A question you should be able to answer if you are following along.

- 'T numbers' (take these loosely please) refer to the weeks of term in which I  intended to cover specific material.
    - For example 'T1:03 - T1:04a' means 'term 2 week three (both lectures) and term 2 week 4, first lecture only'


\


Margin notes:

<div class="marginnote">
These reflect brief comments, hints, side points, or reference links.

</div>


\

Folding boxes:

I will occasionally put additional material in boxes that can be unfolded. Sometimes I do this with "question and answer" so you've an opportunity to consider the answer before peeking. I also will do this with some material that involves a side conversation, or material that is very tangential.

Look in the fold:

```{block2,  type='fold'}

Greetings from the fold! The weather is nice in here.
```

<!---
batch file: 'bash \$HOME/"Google Drive/exeter_teaching/be2024/compileslidesnotes.sh"'
-->

<br> \bigskip

### Tech details of this book ('do I call this 'collophon'?)

I created this in Rmd (the 'R languages' 'markdown'), including some latex and html code too.

This is all put together by  Knitr and Bookdown using the 'Pandoc' conversion tool into an Html file which I'm hosting via Github pages for now.

I'll occasionally use/show some R code; you should consider getting proficient in R and developing other 'data-sciencey' tech skills (things like R, Python, Stata, git, vim, shell scripts...)

Let me know if you want to look 'under the hood'...

```{block2,  type='fold'}

All source material and code can be accessed [on my Github repo](
```


## Outline and description of module {#outline}

**Planned syllabus, coverage:**

*The planned module outline is below;  as noted, timings may need to be adjusted,  and so material may cut for time constraints.  Feel free to skip over the first time you read these notes; you may want to refer to this later. The relevant part of this outline will be repeated at the beginning of each 'section.'*

- **Module outline, overview, some broad discussion and background, Economic models (and maths tools), 'empirical' evidence** (\*) [1a] [First lecture](intro-lecture)

    - McAfee et al ('McDL'), Chapter 1
    - Aside: discussion of 'empirical identification': [The mixtape, Scott Cunningham](http://scunning.com/cunningham_mixtape.pdf) pp 18-22
    - Math revision concepts in
        - [DA lecture 3](https://ocw.mit.edu/courses/economics/14-03-microeconomic-theory-and-public-policy-fall-2016/lecture-notes/MIT14_03F16_lec3MathTools.pdf); we may not use all of this
        - QMC 1.3 (some good stuff; don't worry too much about all the derivative rules)

<!--  `r format_with_col("First problem set: Mathematical approaches, economic models, revision and warm-up; (to add: some practice MCQ's)","blue")`
I will put up slides and other resources to help you with this (and we will re-cover some of this when we apply it throughout the module). The maths you need will also be simultaneously covered in your Optimisation and Econometric modules.
-->

- Supplementary reading:
    - Friedman, Milton. "The methodology of positive economics." (1953): 259. *Classic but perhaps outdated*
    - [Sugden, Robert. "Credible worlds: the status of theoretical models in economics." Journal of Economic Methodology 7.1 (2000): 1-31.](https://www.tandfonline.com/doi/pdf/10.1080/135017800362220)
    - [Sugden, Robert; Sitzia, Stefania. "Implementing theoretical models in the laboratory, and what this can and cannot achieve."  Journal of Economic Methodology, Vol. 18, 2011, p. 323-343.](https://ueaeco.github.io/working-papers/papers/cbess/UEA-CBESS-11-08.pdf)

\


- **[Utility and choice](util-choice)** (Utility, preferences, indifference curves, budget constraints ...) [1b-2]
    - McDL: Ch 12, plus 'preference relations', Ch 20: Math: Deriving supply and
demand curves (demand part), esp 20.3
    - AUT: [Lecture 3 - Axioms of Consumer Preference and the Theory of
Choice](https://ocw.mit.edu/courses/economics/14-03-microeconomic-theory-and-public-policy-fall-2016/lecture-notes/MIT14_03F16_lec3.pdf) (note, slightly different notation)
    - NS: Ch 2
    - **T1:01b, 2**
    - Second problem set or mock exam

- Supplementary reading:
    - Loomes, Graham, Chris Starmer, and Robert Sugden, 1991."Observing Violations of Transitivity by Experimental Methods". [jstor link](https://www.jstor.org/stable/2938263?seq=1#metadata_info_tab_contents)
    - Choi, Syngjoo, et al. "Who is (more) rational?." The American Economic Review 104.6 (2014): 1518-1550.a.
    - Waldfogel, Joel. "The deadweight loss of Christmas." The American Economic Review 83.5 (1993): 1328-1336.
    - [Reinstein, David. "The Economics of the Gift." (2014; working paper and chapter in Gift Giving and the'embedded'Economy in the Ancient World, F Carlà, M Gori - 2014).](https://core.ac.uk/download/pdf/74369736.pdf)
    - D. Colander \\Edgeworth's Hedonimeter and the Quest to Measure Utility'' Journal of Economic Perspectives, Spring 2007: 215-225.
    - [Sugden, Robert. "Looking for a Psychology for the Inner Rational Agent." Social Theory and Practice 41, no. 4 (2015): 579-98.](http://www.jstor.org/stable/24575750).
    - [‘Predicting Hunger: The Effects of Appetite and Delay on Choice’; Read and van Leeuwen, 1998](https://www.sciencedirect.com/science/article/pii/S0749597898928035) ... and related work... worth getting a sense of this, particularly in the context of the Sugden (2015) reading, such as [Kahneman and Richard H. Thaler. 2006. "Anomalies: Utility Maximization and Experienced Utility." Journal of Economic Perspectives, 20 (1): 221-234](https://pdfs.semanticscholar.org/2899/d2516fb877da40c4a7b95fe0b084a103b9bf.pdf)



***

-  **Demand curves** (individual and market, and properties of each) (\*) [3-4]
    - NS: Ch 3
    - DA: [Lecture Note 6 – Demand Functions: Income Effects, Substitution Effects, and Labor Supply](https://ocw.mit.edu/courses/economics/14-03-microeconomic-theory-and-public-policy-fall-2016/lecture-notes/MIT14_03F16_lec6.pdf), esp. sections 1-3
    - McDL:  3.1 (elasticity), parts of Ch 12; Warning: this books treatment of consumer surplus seems to be incorrect (or at least vastly oversimplified) from my PoV
    - QMC: Chapter 17 (elasticities -- very clear treatment, Chapter 18 (supply and demand details)
    - Second problem set (or mock-exam)


- **Production, costs**  (Production functions, isoquants, RTS, scale, types, choice of inputs, LR and SR) (\*) [5]
    - McDL: Ch 9, 'Producer theory - costs' (parts, esp. 'Production Functions'), Ch 10 'Producer theory - dynamics' (parts, esp. 'Economies of Scale and Scope')
    - NS: Ch 6-7 (parts)
    - QMC: Ch 20 (supply part)
    - T1:04

- Supplementary reading:
    - Garber, Alan M., and Jonathan Skinner. "Is American health care uniquely inefficient?." The Journal of Economic Perspectives 22.4 (2008): 27-50.

- **Profit maximisation and supply, Perfect competition in a single market** (Firms, MR=MC, shut-down, (Brief: Supply curve, entry/exit, CS and PS, tax incidence)) (\*) [5b-6]
    - NS: Ch 8-9
    - McDL: - Ch 10 'Producer theory - dynamics' (parts, esp 'Reactions of Competitive Firms', 'Dynamics with constant costs', 'General Long-Run Dynamics')
    - T1:5-6a (continued)

- Supplementary reading:
    - Gibbons, Robert. "Four formal (izable) theories of the firm?." Journal of Economic Behavior & Organization 58.2 (2005): 200-245.

- ** General equilibrium and welfare (brief)** (interrelated markets and equilibrium prices, efficiency of perfect competition, failures) [6b]
    - Main resource: this handout
    - NS: Ch 10 (parts)
    - DA: [Lecture 10 General equilibrium in a pure exchange economy](https://ocw.mit.edu/courses/economics/14-03-microeconomic-theory-and-public-policy-fall-2016/lecture-notes/MIT14_03F16_lec10.pdf)
    - McDL: Ch 14 (parts)
    - QMC: Ch 21; 'Transition: Welfare Economics' ... an interesting narrative
- `r format_with_col("Third problem set: Costs/production, perfect competition in a single market, Welfare/General Equilibrium ","blue")`

- Supplementary reading:
    - Slonim, Robert, Carmen Wang, and Ellen Garbarino. "The market for blood." The Journal of Economic Perspectives 28.2 (2014): 177-196.


***

<!---
 **WILL SKIP: Market failures: Asymmetric information** (Moral hazard, adverse selection, signaling)
-->

- **Market failures: Public goods** (attributes, equilibrium underprovision, remedies) [6b-7a]
    - McDL: Ch 8 -- public goods
    - NS: Ch 16 -- public goods section only, possible supplements on voluntary provision of PG/charity
    - T1:06b-7a
    - `r format_with_col("Fourth problem set: Public goods ","blue")`

- Possible supplementary reading (these will be updated):

Chaudhuri, 2009. Sustaining cooperation in laboratory public goods experiments: a selective survey of the literature

Ledyard, J.O., 1993. Public Goods: A Survey of Experimental Research, Division of the Humanities and Social Sciences, California Institute of Technology.

Vesterlund, Lise. "Voluntary giving to public goods: moving beyond the linear VCM." Handbook of Experimental Economics 2 (2012).

Vesterlund, Lise. "Using Experimental Methods to Understand Why and How We Give to Charity." The Handbook of Experimental Economics (2013).

Varian, Hal R. "Buying, sharing and renting information goods." The Journal of Industrial Economics 48.4 (2000): 473-488.

- **Monopolies, pricing and price discrimination** (single firm with market power; leads to another market failure) [7b-8a]
    - McDL: Ch 15 -- Monopoly
    - NS: 11.2-11.4
    - QMC: Appendix A.1 - Monopoly - the vanilla version
    - T1:07b-8a
    - Article: [Should we help companies tailor prices to your wage packet?](https://theconversation.com/should-we-help-companies-tailor-prices-to-your-wage-packet-47719)
    - With accompanying [worked examples](https://docs.google.com/document/d/16jos_PT9w1wGpyD5A8ZiWJ9HW6kaLOJH6EWc_AYWnkk/pub)
    - More advanced: 'The Government May Want to Encourage Price Discrimination by Income' [Linked here](https://davidreinstein.wordpress.com/research-and-publications/)

- `r format_with_col("Fifth problem set: Monopolies and price discrimination","blue")`

<!--
- ** Imperfect competition (brief) ** (multiple firms with market power; esp Bertrand/Cournot models)
-->

***

- **Uncertainty** (basic concepts, EU, risk aversion, investment choices) [8b,9a]
    - DA: [Lecture Note 16: Uncertainty, Risk Preference, and Expected Utility Theory](https://ocw.mit.edu/courses/economics/14-03-microeconomic-theory-and-public-policy-fall-2016/lecture-notes/MIT14_03F16_lec16.pdf)
    - NS: Ch 4 (not including 4a)
    - McDL: Ch 13, section 4 'Risk Aversion'
    - QMC: Ch 5 (does not use utility functions, but good discussion of diversification)
    - T1:08b-9a

    - `r format_with_col("Sixth problem set: Uncertainty (Chapter 4)","blue")`

- Supplementary reading:
  - Holt, C., and S. Laury (2002), Risk Aversion and Incentive Effects, American Economic Review, v. 92 (5): 1644-1655.

- For a popular audience: Reinstein (2016) 'Should you hedge your bets on a Brexit?' [LINK](https://davidreinstein.wordpress.com/2016/06/19/should-you-hedge-your-bets-on-a-brexit/)

- **Game theory (and lab experiments)** (*Strategic* interaction) [9b,10]
    - QMC: Ch 9, 10, 12 (includes 'iterated dominance')
    - McDL: Ch 16
    - NS: Ch 5 (parts)
    - Several additional concepts from handout, plus supplement on experiments
    - T1:09b-10

-  `r format_with_col("Seventh problem set: Game theory (chapter 5, plus a few additional concepts covered in lecture)","blue")`



- Supplementary reading:
    - Spence, M. (1973): 'Job market signaling,'? The Quarterly Journal of Economics, vol. 87, pp. 355-374.
    - 'Ten Little Treasures of Game Theory and Ten Intuitive Contradictions' Goeree and Holt, 2001

- **Asymmetric information** (Moral hazard, adverse selection, signaling)
  - Separate notes/handouts, to be integrated in
  - Readings tbd

- **Behavioural economics** -- first lecture (limits to cognition, willpower, self-interest), second lecture (applications) [11]
    - NS: Ch 17, plus supplements
    - T1:11
    - Further readings tbd
    - `r format_with_col("Eighth problem set: Behavioural economics","blue")`


Overall each reading is optional, but to do well on the exam you need to do at least some of these readings, and/or cover some of the more advanced material.


- Supplementary reading: theory
    - Amos Tversky & Daniel Kahneman, 1979. "Prospect Theory: An Analysis of Decision under Risk" (*Seminal*)

- Supplementary reading: applications and empirical work
    - DellaVigna, Stefano. "Psychology and economics: Evidence from the field." Journal of Economic literature 47.2 (2009): 315-372.
    - Benartzi, S. & Thaler, R.H., 2007. Heuristics and biases in retirement savings behavior. The journal of economic perspectives, pp.81-104.
    - Farber, H., 2008. Reference-dependent preferences and labor supply: The case of New York City taxi drivers. The American Economic Review. Available at: http://www.ingentaconnect.com/content/aea/aer/2008/00000098/00000003/art00021 [Accessed November 19, 2015].
    - (Behavioural insights team) EAST: Four simple ways to apply behavioural insight
    - Kellner, Reinstein and Riener, 2016. [Conditional generosity and uncertain income: Field and lab evidence](https://dl.dropboxusercontent.com/u/91553/Giving_and_Probability.pdf)
    - Material linked at [giveifyouwin.org](giveifyouwin.org)

***

- **Revision lecture, catch-up**
    - T1:12a




