# Preferences, Utility and Choice {#pref-util-choice}


What can we reasonably say about 'what people prefer and choose'? How can we state this carefully and precisely? What are the implications of particular 'reasonable' assumptions? (How) can we consider this in terms of 'optimization'? How have Economists and decision-scientists considered these questions?


```{block2,  type='note'}
Digging deeply into the logic and justifications for these models of choice, and alternative frameworks, will be very relevant in considering Behavioral Economics (This is a specialty of Ariel Rubinstein, one of the O-R text's two authors, and also a research interest of mine). In fact this text works behavioral economics in from the beginning.

This is also relevant for building empirical models such as 'models of consumer choices and preferences' in ways that are relevant to (e.g.) Business-data-analytics consulting.

```


<!-- This will take at least two weeks to cover meaningfully. -->



```{block2,  type='note'}

We approach this in an abstract and logically and mathematically-rigorous, but not highly 'computational' way. Even if you have taken Economics as an undergraduate, you may not have seen this approach.

We will not always be quite so mathematically rigorous throughout the module. However, I want to at least give you some of these tools, and a 'flavour' of this approach, which characterises modern Microeconomics (and will be at the core of PhD modules).

```

<!--`-->

## Reading {#reading-prefs}

**Main reading** (largely integrated into web book):

- O-R Chapters 1-2 (we will focus on selected material as described in this web book, but feel free to read these chapters in their entirety if you find it interesting; it all may be useful for your project, dissertation, and future work and study)

*Note:* *Within O-R chapter 1, feel free to skip*  the proof of propositions 1.1 ('representing preferences by utility functions') and 1.2 ('Preference relation not represented by utility function')

\

\

Alternative treatments for some of this material (read this if you need a different approach than the ones O-R are taking)... unfold

```{block2,  type='fold'}


- [McDL](https://www.kellogg.northwestern.edu/faculty/dale/ieav21.pdf): Ch 12, plus 'preference relations'

[Here](https://www.dropbox.com/s/tjs1l32at0dd1as/ieav21%20-dale%20micro.pdf?dl=0) is a version we can write dropbox notes in

- AUT: [Lecture 3 - Axioms of Consumer Preference and the Theory of
Choice](https://ocw.mit.edu/courses/economics/14-03-microeconomic-theory-and-public-policy-fall-2016/lecture-notes/MIT14_03F16_lec3.pdf) (note, slightly different notation)

- NS: Ch 2


```

### Readings: 'real research papers' {-}

Supplementary and conceptual readings (please read at least *some* of these):


- [Sugden, Robert. "Looking for a Psychology for the Inner Rational Agent." Social Theory and Practice 41, no. 4 (2015): 579-98.](http://www.jstor.org/stable/24575750).

- D. Colander 'Edgeworth's Hedonimeter and the Quest to Measure Utility'' Journal of Economic Perspectives, Spring 2007: 215-225.

- [‘Predicting Hunger: The Effects of Appetite and Delay on Choice’; Read and van Leeuwen, 1998](https://www.sciencedirect.com/science/article/pii/S0749597898928035) ... and related work... worth getting a sense of this, particularly in the context of the Sugden (2015) reading, such as [Kahneman and Richard H. Thaler. 2006. "Anomalies: Utility Maximization and Experienced Utility." Journal of Economic Perspectives, 20 (1): 221-234](https://pdfs.semanticscholar.org/2899/d2516fb877da40c4a7b95fe0b084a103b9bf.pdf)
ial treatment)


### Interactive exercises ('problem set') {#pref-exc}

To be determined ('tbd'). Some possibilities below the fold.

```{block2,  type='fold'}

1. Discussion and writing on the realism of particular assumptions and on 'observing preferences and observing violations of transitivity'

2. Preferences and utility: Definitions, proofs, and sketched examples -- Problems and exercises

Question 6 on the "Shepard scale" is very cool!
\

### Content

```{block2,  type='note'}
**I will add a great deal of content here shortly.**

This will go through the relevant OR text material and a bit more.
```


```



