# Beem101: Project, discussion of research {-#project}


```{block2,  type='note'}

BEEM101 Autumn 2020 students: Please fill out the anonymous survey questions on the [Final project channel on the Teams team](https://teams.microsoft.com/l/channel/19%3a2b075cd7fa57452f8f75266d9088895c%40thread.tacv2/Final%2520project?groupId=68890d91-9fed-46ab-a491-267df512c21a&tenantId=912a5d77-fb98-4eee-af32-1334d8f04a53)

```

\

## Description from ELE page:

60% of mark: "Final project and presentation"

The point of this project and presentation (unfold):

```{block2,  type='fold'}

These are not meant to be dissertations or major pieces of original work. The idea is simply to demonstrate your understanding and ability to apply material from this module, particular the second half of the module. I also want this to be a stepping stone, to help you learn to apply microeconomic theory in your dissertation and career research work.

I am asking you to present this to me because I think that provides a great opportunity for feedback and for you to demonstrate your personal mastery and understanding of this material. Particular in a world without invigilated examination, I want to give you the chance to really show off your strength.

```  

\

Several options (discussed below):  all ask you to 'explain, assess and apply microeconomic theory'.

I will arrange group or individual meetings in Late-November or Early December for you to tell me your proposed topic and group, and for us to discuss this. 

The project must *not* principally involve material covered in the midterm (and obviously please do not copy content from the lecture materials/web book/textbooks): it must involve Game Theory and/or enrichment/supplemental topics (which may include price-discrimination and/or asymmetric information).


- All projects must include and explain some formal economic modeling (with maths), showing your understanding and insight. In other words, you *must* demonstrate your understanding of Microeconomics and your ability to apply it in some way.

- All projects must cite and explain *at least two* peer-reviewed academic Economics articles (and perhaps more).

- Ideally, these projects will relate to your proposed dissertation (if your programme requires you to do one), or to your career goals

\


**Rules and dates (for Autumn 2020 Exeter students)**

To be submitted by `r format_with_col("11 January", "red")`  

- Written length: approximately 8-12 pages, 5000-7000 words; for group projects add 5 additional pages to the maximum per additional member of the group, up to 30 pages for a four member group.

- If it is submitted as a group project each student must also submit a one-page description of the project and their contribution to it


- Spoken presentation (with slides if desired): 8-10 minutes plus 4-5 minutes discussion and feedback (group presentations may take slightly longer)

- Presentations to be scheduled and take place (online on Teams or in person if health conditions permit) by 15 January  (subject to confirmation)

- Alternative: You can instead give a presentation *before* submitting your project; this may help as it will enable you to gain feedback in advance of your submitted project. 

- For group work, each student must present part of the work to me and respond to at least one question 


\

**How to structure the project (a rough sketch, not 'the only way')**

```{block2,  type='fold'}

I was asked about the 'structure' of the project. This depends on the option, on your topic choice, and on how you wish to pursue it. Nonetheless, a rough structure might look like the following:

  \

1.  Introduce the topic, model, question, overview of what you are going to do, and why this is relevant and interesting (some combination of this)

The Economic theory/theories and model(s) presented...

- with reference to academic authors (papers, textbooks)  
- using formal (maths) modeling, giving at least one simple but formal presentation, and explaining it clearly and in your own voice (remember to explain what all variables mean),  
- considering the *assumptions* and simplifications of the model,  
- the 'Economic tool/fields considered' (e.g., optimisation, equilibrium)  - the sensitivity of the 'predictions' to the assumptions  
- the justification for these assumptions  
- and the relationship between this model and your (applied) topic or focus... are the assumptions relevant, what are the 'predictions' etc. 

\

2. The application or real world example:
	
- Explain it in practical terms and what the 'issues and questions are' (possibly engaging the previous literature a bit, but not too much as this project is mainly about the *theory and modeling*),

- describe and express it formally,

- relate it to the model/theory and apply the model theory to your real world example,

-  and try to 'model it' and derive 'results' or predictions, continually justifying the application of the model to the example.
	
\

3. Presenting and assessing the insights from the model for the application and vice/versa
	
- considering the relevance and sensitivity,
- considering which alternative models/assumptions might be used, and how might it be adjusted,
- discussing 'what modeling and theory achieved or did not achieve here'
	
	
Note that "2" could come before or after "3" ... you can present the application first, or the model first... (or there may even be a way to go back and forth between the two, presenting one part of each, as long as this doesn't get confusing).

```

## Option 1: Game Theory: Characterization and analysis of a real-world situation/problem/issue

Consider a real-world situation, problem or issue involving strategic interaction.  Characterize and analyse this using the tools of microeconomics and game theory (or principle-agent models and mechanism design.)  You may get some ideas from the game theory material and [exercises in this web book](#gt_strat_ex) and O-R, but obviously it most go further than this. 

\


One possible (approximate) structure for this project: 

*Introduction* 
1. State and briefly describe the topic. If possible, briefly explain why it is important, relevant, or interesting (for policy, for business and management, or for considering human behavior, or otherwise).

\

*Model the behaviour/outcome*  \*

2. Set up the problem (game theory: players, strategies/actions, payoffs, information structure)

3. List your assumptions

4. solve and interpret the model (game theory: define and explain the 'solution concept' you are using)

<div class="marginnote">
\* Note: you may find it most feasible to construct this by adapting an existing applied model to your particular question. Please reference any work you have adapted, and discuss how you have adapted it.
</div>
 
\

*Discussion*

6. Discuss the 'results' of the model (any insights, anything that the predictions crucially depend on)

7. (If applicable) What policy can lead to better outcomes? (e.g. increasing/decreasing a key variable, or changing incentive structure)

8. What are some limitations of your model? How may they affect your results?

\

Some projects that I somwhat randomly found on the web that are sort-of like what I have in mind (but usually these are whole theses, much more than I'm expecting from you here):

```{block2,  type='fold'}

[Mixed Strategy Equilibrium in Tennis Serves](https://econ.duke.edu/sites/econ.duke.edu/files/file-attachments/Wiles%2C%20Joel%20-%20Honors%20Thesis.pdf) -- This is a whole undergraduate dissertation. Much more than you are expected to do for this assignment. But your assignment could resemble some parts of his literature survey plus some parts of the simple model that he presents before doing the empirical analysis.  (And I like the close connection between theory and empirics here, and the way he shows a strong grasp of the literature!)


\

[In this honors undergraduate thesis](https://web.archive.org/web/20150828040526/http://economics.stanford.edu/files/Theses/CasatrinaLeeHonorsThesis-May2014.pdf) the comparison of the 'Lojack' and 'Cybersecurity model' seems interesting and well-explained, fairly straightforward, and not too mathematically intricate.  
\


[The Price of Anarchy in Network Creation
Games Is (Mostly) Constant](http://www.cs.tau.ac.il/~fiat/cgt12/GameTheoryProject.ItzikMalkiel.pdf) -- I'm not familiar with the content. The maths is  more advanced than I'm expecting (these seem to be maths students), and the description is not as complete as I'd like.  But the length and coverage are sort of in the right direction.


```


\

Some references that may be helpful:

```{block2,  type='fold'}

Jog your mind ... think of [films](https://www.gametheory.net/popular/film.html)

\

[A Public Dilemma: Cooperation with Large
Stakes and a Large Audience](http://repository.essex.ac.uk/9979/1/dp617.pdf)

Game theoretical analysis of a game show game 'Golden Balls'; great use of game theory considering social preferences, applied to an empirical analysis. Real academic work (professors) but very readable. I have some slides [here](https://www.dropbox.com/s/zjpys23uyoblqr0/notesonbelotforclass_handout.pdf?dl=0).


```



## Option 2: Asymmetric information/agency theory/mechanism design: Characterization and analysis of a real-world situation/problem/issue

(As in option one, but for Principal-agent models/mechanisms (see, e.g., the supplement on [asymmetric information](#asymmetric)); this usually implies a 'contracting' situation.)

\

Models in this category sometimes have overlap with game theory, but...

One of the important distinctions is the assumption that *contracts can be written and enforced.*

\

We often focus on the characteristics of this contract (or pricing scheme, or 'direct mechanism', or screening and signaling institutions etc). 

\

We may consider how it may be set

- to optimise the goals (profit, social welfare etc) of the Principal or 'designer',

- subject to 'incentive compatibility' (and 'participation' or 'rationality') constraints as well as other potential constraints such as 'limited liability'.

\

And we consider how the outcomes of this optimal (or often "2nd best") contract...

- meet social welfare criterion, 

- what the outcomes are (who gets what, what is produced or implemented), and

-  how this is affected by changes in the conditions and parameters ("comparative statics"). 

\

*Asymmetric information* and associated setups may involve:

- Hidden actions $\rightarrow$ (e.g., 'moral hazard')

- Hidden information $\rightarrow$ (e.g., 'adverse selection', 'information rents/privacy')

- Both 

- Incomplete contracting (e.g., involving unknown unknowns), imperfect bargaining, and 'transactions costs'

\
Some projects that are a bit relevant (see above caveats)

```{block2,  type='fold'}
 
[Deterring Inefficient Gambling in Risk-Taking
Agents](https://sites.duke.edu/econhonors/files/2015/06/Ryan-Westphal.pdf): the model in section 3 is a much more ambitious version of what I would love to see here. 

\

[Incentive Programs for Neglected Diseases](https://sites.duke.edu/econhonors/files/2020/05/ganapathy2020.pdf) - much more intricate than I'm expecting from you. But the modeling of the payoffs is rather nice and straightforward. 

\

Some of my own recent and ongoing work: 

[“Listen to the market, hear the best policy decision, but don’t always choose it,” (with Joon Song [SKKU])](https://ore.exeter.ac.uk/repository/handle/10871/36180)


```


## Option 3: Application of economic theory to (observational) empirical work (econometric/statistical analysis)

Econometricians collect and use data, and seek to 'identify' particular parameters and relationships, often seeking 'causal inference'.

Consider a *particular* empirical question or policy issue (in Economics or an adjacent area). Conduct a brief survey to identify and characterise the work that has been done in this area. (But please do not go into too much detail in writing about this, if it does not relate to microeconomic theory). You may want to focus on a small number of papers.

Explain how microeconomic theory *influences* the statistical/econometric framing and analysis of this question, and the interpretation of the results. What theoretical models (e.g., of consumer and firm choices, government policy goals, strategic interactions, asymmetric information, institutions and market structures) do they use to 'motivate' their question and justify their empirical econometric approach. Specify and explain these models carefully. Consider how these inform the authors empirical analysis. (E.g., the authors may justify their analysis by stating 'this technique identifies the following parameter under the assumptions of the so-and-so model'.)

*See discussion [HERE](https://daaronr.github.io/writing_econ_research/theory-modeling-empirical.html#from-theory-to-empirical-work) on how theory and models can inform applied questions and empirical work


Explain and critique the authors' claims and justifications. If possible, consider the *difference* between the approaches of several authors, contrasting and evaluating their claims and arguments.\*

<div class="marginnote">
\* If you like, you can use this as an opportunity to propose and present your *own actual* analysis of data, but this is not necessary; the focus should be on the theoretical modeling and assumptions, not the empirical analysis.)
</div>
 
## Option 4: Comparison of 'Economic experiment' designs (lab or field experiments) guided by Microeconomic theory

Please consider a question or issue in microeconomics that may be addressed through the use of an experiment, whether a laboratory or field experiment. Find several papers that attempt to do this. Explain how their designs reflect economic theory and assumptions, presenting and explaining the relevant economic theory and models. Comparing these papers, discuss the relative strengths and weaknesses of their designs in providing evidence on the question of interest. If you like, you may propose and make a case for an alternative experimental design or approach.


```{block2,  type='fold'}

[This undergraduate thesis](https://web.archive.org/web/20150828040623/http://economics.stanford.edu/files/RobertCortesHonorsThesis-June2013.pdf) does a great job of:
  
1.. Explaining the Allais paradox and the alternatives to EU theory that may explain such behavior
2. Discussing the prior evidence on this
3 Proposing (and running) an experiment measuring how whether decisions in pairs are less likely to make choices in line with this paradox 
  
The student engages and discusses the theory very well. Again, I'm not asking you to write a thesis but if you can do any of the above three components in a reasonable way (for your chosen question), that would be great.

  
```

\

Some potentially helpful references:

```{block2,  type='fold'}

[@lonnqvistMeasuringIndividualRisk2015; @sitziaImplementingTheoreticalModels2011; @wolbertMeasuringTimeRisk2013]


Goeree and Holt: "Ten Little Treasures of Game Theory and Ten Intuitive Contradictions"

\

"Psychology and economics: evidence from the field"

\

"Handbook of experimental economics" (various editions)

[@cooperOtherRegardingPreferences2009]

"Handbook of experimental economic results"

```


## Option 5: Explanation of another 'advanced concept' in Microeconomic theory (not covered in midterm), application to a real-world situation/problem/issue (or a deep theoretical question involving human values and behavior)

In the notes and readings I mention 'enrichment' and 'advanced' concepts. If you choose this option, your project should explore one of these concepts further. For the concept you choose, please present the formal models clearly and explain these 'in your own words'. Discuss the insights these models provide. Discuss the differing approaches and 'controversies' surrounding these models. Provide and explain an example of how this concept applies (and perhaps 'how it has been applied by researchers') to either a  real-world situation/problem/issue, or to a 'deep question informing our understanding of human values and behavior, and aggregate social and market outcomes'.


```{block2,  type='hint'}

One model for writing this: try to emulate one of the more in-depth Wikipedia articles. (But don't choose a concept that already *has* a good Wikipedia article)

```  

## Option 6: Real-world pricing and segmentation (or other forms of price discrimination) behavior asessed in light of economic theory

Consider the pricing policies of a particular firm, industry, sector, or 'pricing guru'. Explain how these policies do or do not resemble the predictions of economic theory. You may want to focus on particular types of 'segmentation' or 'price discrimination.'

<div class="marginnote">
I want 'something from the real world' either a specific company or a specific set of companies, or price optimization tool, etc,
</div>
 

See references in section \section{#actual-pricing} [above](#actual-pricing).


## Other options:  You can propose another project that doesn't exactly fit into the categories above. BUT ...

If you do so, please do so by early November, and obtain my tentative approval. I want to make sure that all projects achieve the goals of demonstrating your understanding and ability to apply Microeconomics. So be careful.






