
# Some key things for midterm (recap)

- How do economists measure and test models,
    - techniques and terms used
    - thoughts on estimating demand and supply curves

. . .


What is the use and interpretation of 'economic theory  and models', how are these tested, readings on this and on relevance for experiments.


<br> \bigskip

<!---
- Note that economists define 'surplus' as excess supply at the prevailing (or enforced) price and 'shortage' as excess demand at the prevailing (or enforced) price
-->



<br> \bigskip

- The 'axioms' over preferences, the justification for these, and what they imply for utility functions


[comment]: <> (101BB)

- Economists' views on 'what utility is'

'Behavioural' challenges to the model of a consistent maximisation

Revealed preference, tests for ciolations of transitivity

[comment]: <> (101EE)


----

- Understand indifference curves and budget constraints well


. . .


- Conditions for consumer optimisation (obviously this is important) including for when a consumer will choose to consume none of a good



- be able to state and solve a simple consumer optimisation problem, considering corner solutions


<br> \bigskip


. . .

- Definitions of 'types of goods' as implied by characteristics of the demand function

- Impacts of price changes (own good, other good) and income on an individual's consumption, and what goes into this and how to depict it.


[comment]: <> (101BB)

- Lump sum principle, deadweight loss of commodity tax, gifts, or price subsidies

[comment]: <> (101EE)

- (Producer and) consumer surplus.


. . .

<br> \bigskip

- 'Applications', especially those discussed both in the assigned text and in the lectures.

----

[comment]: <> (pre2018BB)

- Firm's conditions for optimisation in input choice.

[comment]: <> (pre2018EE)

- Firm's conditions for 'what quantity to choose' under different market conditions (price-taking, non-price-taking)

[comment]: <> (101BB)

- Which production functions have CRS, IRS, etc

- *Why* IRS, DRS, etc?

[comment]: <> (101EE)


. . .

<br> \bigskip

- Perfect competition in the LR and the SR, what profits look like, how prices move.


. . .




[comment]: <> (101BB)

We will return to  Market failures: Asymmetric information later on


----




