# Prior exams with answers and 'mock exams' {-}

<div class="content"><h3 class="sectionname"><span><span class="inplaceeditable inplaceeditable-text" data-inplaceeditable="1" data-component="format_topics" data-itemtype="sectionname" data-itemid="168372"
    data-value="Mock exams/assessments for 2019-20; Previous years&#039; exams/assessments, formative assessments, and class tests (midterms), with answers" data-editlabel="New name for topic Mock exams/assessments for 2019-20; Previous years&#039; exams/assessments, formative assessments, and class tests (midterms), with answers" data-type="text" data-options="">
        <a href="https://vle.exeter.ac.uk/course/view.php?id=7890#section-3">Mock exams/assessments for 2019-20; Previous years' exams/assessments, formative assessments, and class tests (midterms), with answers</a>

</span></span></h3><div class="section_availability"></div><div class="summary"><div class="no-overflow"><p>Material below includes mock exams and rubrics for 2019-20 previous exams with suggested answer guidelines,&nbsp;formative assessments,&nbsp;problem sets with suggested answers, surveys, other readings. More formative assessments will be added throughout the term. Note coverage varies&nbsp;<em>somewhat</em>&nbsp;from year to year. (Exams before 2016-17 are&nbsp;<em>not</em>&nbsp;highly&nbsp;relevant.)</p><p><br></p><p><b><a href="https://www.dropbox.com/s/r3fck894wsf5qpr/be2038midterm_2019_wans.pdf?dl=0">2019-20 midterm with answers</a></b></p><p><b><br></b></p><p><b>Mock exams/assessments for 2019-20</b></p><p><span><a href="https://www.dropbox.com/s/4z9nlqpzzlh756p/mock_be2038midterm_2019_noans.pdf?dl=0">Mock 'midterm' (late October 2019 assessment)</a>&nbsp;...&nbsp; (version without answers)&nbsp;</span></p><p><span></span></p><a href="https://www.dropbox.com/s/8me10vp96vcqzfd/mock_be2038midterm_2019_wans-extended.pdf?dl=0">Mock 'midterm' (late October 2019 assessment)</a>, with answers, explanation, discussion<p><br></p><p><i><a href="https://www.dropbox.com/s/373isujolu8d2lk/pre-midterm-quiz_for_students.pptx?dl=0">See also the&nbsp;("Second annual Pre-midterm championship" Quiz HERE as a powepoint file, with answer explanations in the 'notes' .</a><br></i></p><p><b><br></b></p>
<p></p>
<p><b>Previous years mid-term exams with suggested answers/explanations&nbsp;</b></p><p><span><i><span class="" style="background-color: rgb(255, 207, 53);">NOTE</span> -- previous version gave the wrong answer for question 12 -- this new version fixes it:&nbsp;</i></span></p><p><a href="https://www.dropbox.com/s/w1x470ie2bt38cr/be2024midterm_2018_wans_fix.pdf?dl=0">2018 midterm, with (MCQ) answers&nbsp;</a>&nbsp;FIXED version</p><p><span style=""><br></span></p><p><span style="">2017-18&nbsp;&nbsp;Midterm answer guidelines&nbsp;</span><a href="https://www.dropbox.com/s/epgdl49g3jwnszq/2024midterm2017-18_withans.pdf?dl=0" target="_blank" style="">HERE</a>&nbsp;</p><p><a href="https://www.dropbox.com/s/cdnpmbhhcteics3/2024midterm2016-17_extendanswers.pdf?dl=0">2016-17 Midterm with answer guidelines</a></p><p><span><span style=""><br><br></span></span></p><p><strong><span>2018-19 exams, mock exams, rubrics etc</span></strong></p>
<p><span><a href="https://www.dropbox.com/s/zuqlw59eulh3xh6/2018_19%20-%20Final%20relevant%20formative%20assessment%20on%20Game%20theory%20and%20Behavioral%20Economics_answers_shown%20in%20yellow.pdf?dl=0">Answers to MCQ formative assessment on Game Theory and Behavioral Economics (see above)&nbsp;</a></span></p>
<p><span>2018-19:&nbsp;<a href="https://www.dropbox.com/s/u2z8inibbfbzqhj/be2024_final_2019_RUBRIC.pdf?dl=0">Final exam rubric (and some hints on coverage)</a></span></p><p><br></p>
<p><span><strong><span>2018-19:&nbsp;<a href="https://www.dropbox.com/s/zh9dplzkv62ucpq/be2024_final_2019_MOCK_noans.pdf?dl=0">Mock Final exam</a>&nbsp;</span><span><a href="https://www.dropbox.com/s/zh9dplzkv62ucpq/be2024_final_2019_MOCK_noans.pdf?dl=0">(no answer guidelines)</a></span></strong></span></p>
<ul>
<li><span><strong><span></span><span><a href="https://www.dropbox.com/s/hsjswci84vhyaic/be2024_final_2019_MOCK_wans.pdf?dl=0">with answer guidelines</a></span></strong></span></li>
</ul><p><b><br></b></p>
<p></p>
<p><strong>2019 exam with indicative answers, general feedback&nbsp;</strong><a href="https://www.dropbox.com/s/q0v9cof27y4ixco/be2024_final_2019_with_frequent_comments.pdf?dl=0">Link HERE</a></p>
<p></p>
<p><span>Relevant previous year's assessments, with suggested answer guidelines</span></p>
<ul>
<li><span><a href="https://www.dropbox.com/s/ppbb89yflsey7n7/be2024fix_wans_2016.pdf?dl=0"><span class="instancename">May 2016 Assessment (Exam), with suggested answer guidelines<span class="accesshide "><br></span></span></a></span></li>
<li><span><span class="instancename"></span></span>
<p><span>2017-18&nbsp;&nbsp;Midterm answer guidelines&nbsp;<a href="https://www.dropbox.com/s/epgdl49g3jwnszq/2024midterm2017-18_withans.pdf?dl=0" target="_blank">HERE</a>&nbsp;</span></p>
</li>
<li>
<p><span>2017-18 MOCK Final Exam&nbsp;<a href="https://www.dropbox.com/s/x024qafqnva2p8x/be2024_final_2018_MOCK.pdf?dl=0">(HERE)</a>&nbsp;[link fixed]</span></p>
</li>
<li><span class="instancename"><a href="https://www.dropbox.com/s/z7gbpwsdei9z6vn/be2024_final_2017_wans_postexam_students.pdf?dl=0">2017 Final with suggested answer guidelines</a>&nbsp;[version fixed]</span></li>
</ul>
<ul>
<li><a href="https://www.dropbox.com/s/oh11df6re9kucab/be2024_final_2018_wans_postexamdetails.pdf?dl=0"><span>2018 Final with suggested answers and extra tips ('common errors' etc)</span></a></li>
