## Third problem set (may add to this): Idividual and market demand curves, properties of these {-}

### Def of a type of goods {-}

Choose ONE.

If, starting with *any* combination of goods A and B, an individual is willing to give up one unit of good A to get three units of good B the two goods are

- A. perfect substitutes
- B.  perfect complements
- C. complements (but not perfect)
- D. substitutes (but not perfect)
- E. Giffen goods


<!-- [comment]: <> (ANSBB)

*Suggested answer* \
1. perfect substitutes
Remember, perfect substitutes can be in *any* ratio, they don't need to be 1-to-1.


[comment]: <> (ANSEE) -->
 


### Impact of price change on a normal good {-}


<!-- [comment]: <> (TABB)

\textcolor{red}{GTA's:}

GTA’s: This would be a good one to cover in tutorial.

2018-19: However, I will have only recently covered this in lecture.

[comment]: <> (TAEE)
-->

Suppose a good is *normal* (in the technical economic sense). Consider the impact on the amount of the good consumed when its price decreases. Which statement is correct?

a.  the income effect will be positive and the substitution effect will be positive. \
b.  the income effect will be negative and the substitution effect will be negative. \
c.  the income effect will be positive and the substitution effect will be negative. \
d.  the income effect will be negative and the substitution effect will be positive. \

\

<!-- [comment]: <> (ANSBB)

*Suggested answer* \
  a.  the income effect will be positive and the substitution effect will be positive. \

For all goods the substitution effect is in the opposite direction as the price change, here positive (as price decrease). As a good becomes relatively more expensive you 'substitute away from it'.


For normal goods the impact of 'greater effective income when the price decreases' will be to increase consumption, ergo 'positive'.
Remember, for normal goods the income effect is always positive.

\

You can remember these rules and answer a question like this, but e.g., on the final, you may need to do more.

To see this graphically...

First for the substitution effect, we need to find the point on the original indifference curve with the same slope as the new budget constraint (price ratio).
`r format_with_col("We depict this by shifting in the new budget constraint ('compensating by reducing income') until it is tangent to the original indifference curve. This is only a 'hypothetical' budget constraint... it is the budget constraint that would result from this type of compensation.","gray")`

We look for this point because the substitution effect 'asks' 'what amount of each good do we consume in the cheapest bundle that yields the original utility at the new price ratio?' If the good on the horizontal ('X') axis becomes more cheaper, the budget constraint becomes shallower, and the point on the original indifference curve with that shallower slope must be down and to the right. ...

Intuitively, more X and less Y will decrease the MU of X and increase the MU of Y, making her willing to give up less Y to get a unit of X. And now that X is cheaper, she *can* give up less Y to gain a unit of X, so we attain this new 'bang for the buck' condition for the 'hypothetical' or 'compensated' budget constraint.

\

For the income effect we can 'start' from the point we have just reached in considering the substitution effect, and move the budget constraint outward until we get to the *actual* new budget constraint. This latter effect is just like a shift in income holding the price ratio constant. That's the same question we ask when we consider 'income effects' and consider whether a good is 'normal' or 'inferior'. As this good (the X good) is 'normal', this shift ('increase in income') must lead to a greater consumption of X.

So both effects are 'positive' here, i.e., both effects cause the quantity of X chosen to increase.

<!-- <!-- [comment]: <> (TABB)

`r format_with_col("GTA's:","red")` At this point you could briefly ask them 'will this be the same for inferior goods'?
[comment]: <> (TAEE)
-->



###Definition of complements {-}



(88\% got it)


Two goods, X and Y, are called complements if \

  a.  an increase in $P_X$ causes more Y to be bought. \
  b.  an increase in $P_X$ causes less Y to be bought. \
  c.  an increase in $P_Y$ causes less Y to be bought. \
  d.  an increase in income causes more of both X and Y to be bought.

<!-- [comment]: <> (ANSBB)

*Suggested answer* \

  b.  an increase in $P_X$ causes less Y to be bought. \

This is just the definition of 'complements'. Just remember this.

Also, to help you remember, think of complementary goods as goods that ‘go together’. So an increase in the price of X causes you to buy less X and also less Y. (This holds unless the good is Giffen; let’s ignore that as a Giffen good is extremely rare or perhaps nonexistent). Less tea is bought, thus less milk is bought.

[comment]: <> (ANSEE) -->


### Restrictions with two goods {-}


(62\% got it)



If there are only two goods it is not possible that (choose all that apply) \

a. they are both luxury goods. \
b. they are both inferior. \
c. one is inferior and one is normal. \
d. they are complements. \
e. they are perfect substitutes.

<!-- [comment]: <> (ANSBB)

*Suggested answer* \
a,b: they are both inferior (is impossible). This would imply that when income increased a person spent less, which could not be optimising. Similarly, they cannot both be luxury goods in the technical sense: as income increases you cannot spend a larger share of your income on both goods.

`r format_with_col("Be careful","red")` \textcolor{gray}{to read the question instructions: I’m asking you to select the two things that are not possible if there are only two goods. Practice responding to questions like these logically and carefully.}


[comment]: <> (ANSEE) -->

###Demand in LR and SR {-}


(68\% got it)


The demand for petrol is more elastic in the long run than in the short run because \

\begin{enumerate}[label=(\alph*)]
\item other prices are more likely to change in the long run.
\item incomes tend to rise over time.
\item people can buy new cars in the long run.
\item cars have become more expensive over time.
\end{enumerate}

<!-- [comment]: <> (ANSBB)

*Suggested answer* \
  c: people can buy new cars in the long run.

In the SR the reaction to the price change is small (less elastic) because people are stuck with their habits and their equipment. In the longer term they could make a lot of major changes, including buying new, more energy-efficient cars (and thus buy even fewer units of fuel).

Remember, things being more expensive or cheaper doesn’t itself tell us about the price elasticity. Price elasticities are about responsiveness to price changes, stated in proportional terms.

`r format_with_col("Note that we also think of supply curves as being more price-elastic in the LR (consider: why?).","gray")`

<!-- [comment]: <> (TABB)

`r format_with_col("GTA's:","red")` If time permits, get them to volunteer some answers to this follow-up question. . . . For example, the labour supply of teachers/teaching hours may be fairly steeply sloping in the short-run (large wage increases are needed to induce retired or part-time teachers to take full time jobs) but more shallow in the long-run (more people will choose to get degrees in teaching if the wages are higher).

[comment]: <> (TAEE) -->

[comment]: <> (ANSEE) -->


***



*Note:* the question below has not been asked on an exam.

However, it is very much like questions that have been asked, and could be asked, on a final exam, in a ‘solve problems and explain’ section. Parts of this could also be framed as a multiple choice. It is somewhat more mathematical than questions you have seen before. For questions like these, I will try to provide options, so that those of you who are comfortable with this sort of maths can choose it, while for those who struggle with it, there will be other options to show your excellence.


