# Notes to students {#note}

## On this online resource and the textbook.

Much of this module follows the textbook
**Nicholson/Snyder, Intermediate Microeconomics and its Application**, 12th edition (other editions are OK too).

This text forms the basis for roughly 80\% of this module. I recommend you purchase, or find easy access to some edition of this book (new editions should be £50, used editions should be cheaper), the publisher also sells an online-only version. In the future I hope to turn this online resource into a full interactive, collaborative, open-access online text, adapting material from other open-access resources, but I am not there yet.

See some alternative and supplemental free texts and resources [BELOW](#texts)


For example, from time to time I will refer you (and draw from) another open source work that has *very clear explanations*:

-  [Quantum Microeconomics... with or
without Calculus](http://www.smallparty.org/yoram/quantum/) by Yoram Baumann, the self-proclaimed 'World's First Standup Economist'



## On this module (Exeter: BEE2038 - Intermediate Microeconomics - for students not doing a straight Economics degree)

*Welcome to the exciting world of Microeconomics!*

I hope that this module helps you see the world in a new way and gain insights about business, government, and your everyday life. If you put the time into this module, you can get a lot out of it, and you may gain skills and access approaches that you will use throughout your career. As students at a Russell group institution, I expect you to work hard and engage intellectually to gain a serious and critical understanding of key Economics concepts. Learn how and when these can be applied, what their limitations are, and how these can these are misused and misunderstood. I hope you learn these core ideas well enough that you could explain them to others and apply them to unfamiliar situations.

This is not necessary to gain a good mark: I hope that you all will be able to gain a good mark, and I will try to be lenient. But I would suggest you aspire to get *more* out of this than a mark.

You should aim not only to achieve a distinction mark, but to be able to impress me with your understanding and insight, to gird your loins  for future courses applying this material, and to gain the acumen to understand key research issues, and participate in business discussions and policy debates.

I wrote these notes to outline all of the material you are responsible for,  and to give you more resources and insight than I can convey in the short  amount of time we have during lecture.   I *don't* mean you're simply responsible for material in these printed notes:  I mean that these notes will aim to *refer to* everything that you are responsible for.

These notes are meant to be a complement to the textbook (and to the lectures,  tutorials/problem sets, readings and other material on the ELE) and to tie all of this together. (However, as I add to these notes I hope to turn this into an open-access textbook that will replace the text.)

<!-- I am providing you these notes both as a complete file as well as divided by lecture week (approximately). Use either version.
-->

 I will try my best to stick to the structure outlined in these notes.  However,  each year the module adjust slightly as we go and I will need to make updates to these notes as we go along.  I will try to keep you informed of any changes via the VLE forums.


<br> \bigskip

*Notes versus slides?:*

These notes should include all of the slide material *plus* explanatory notes and enrichment material. (However, I left out some of the jokes.) I use some abbreviations before certain notes to help you understand how to digest this.  I will also try to make the slides themselves available after the lectures,  even though they are redundant– these notes have everything.^[Still, every year students request it.]

<br> \bigskip


*Some 'markers' and abbreviations:*

- 'NS'  refers to the Nicholson and Snyder text (usually chapters/numbering from the 12th edition is referenced;  if you're using an earlier edition, make sure the content corresponds)



- `r format_with_col("'Adv'","RawSienna")` indicates advanced material and discussion you are not required to know but may find interesting, and will help you in later courses/modules in Economics, and give you a hint at what is to come if you pursue this course further. Knowing  this stuff might also help your mark and the impression you make when asking for letters of reference.
    - This is also included to give you a more nuanced picture: when I took a similar module as an undergraduate I tended to believe 'all the economics problems are solved and the solutions and implications are obvious.' These 'Adv' comments are often caveats and *critiques*.

`r format_with_col("'Adv, math'","RawSienna")` indicates advanced mathematical material. (I've moved most of this to footnotes).

`r format_with_col("Text in blue usually refers to questions you should  try to answer on your own (and I sometimes provide suggested answers in the footnotes. Try to answer it yourself first.)","blue")`

`r format_with_col("Some text is given in gray to indicate that this is a side point or a discussion. (I'm moving most of this to footnotes.)","gray")`


- 'Comprehension Q:' A question you should be able to answer if you are following along.

- 'T numbers' (take these loosely please) refer to the weeks of term in which I  intended to cover specific material.
    - For example 'T1:03 - T1:04a' means 'term 2 week three (both lectures) and term 2 week 4, first lecture only'


<!---
batch file: 'bash \$HOME/"Google Drive/exeter_teaching/be2024/compileslidesnotes.sh"'

-->



## Course Information

*Some quick notes on this module and how it fits into your course structure*


This module is:

- Compulsory for BSc Business Economics and BA Business Economics
- Also for PPE I believe

The prerequisites are BEE1029 (for most students) or BEE1034 or BEE1030 and BEE1031


The prerequisites are very different, the students in this module may come from diverse *backgrounds*.

We will try to focus on material:

- not covered in BEE1029 or
- more rigorous and detailed versions of this, and
- real world applications, especially in business.

Some of you may have already seen some of the material covered here.
If so, try to learn it in more detail, become better at explaining  it to others, and learn to apply it to real-world issues.


<br> \bigskip

*Note: From 2020 onwards, all students in this module will come from the "CORE ESPP"*

\url{https://www.core-econ.org/espp/}

You may also find this to be a useful resource, for revision, motivation, and as a supplement to the Nicholson/Snyder text

(Also, see "The Economy" 1.0) \url{https://www.core-econ.org/project/core-the-economy/} for more straight Economics

<br> \bigskip

*A note on maths*:

As I will explain, this course will involve a certain level of maths;  things like simple algebra, understanding what functions are and how to draw them,  and understanding the very basic idea that 'the derivative of a function is a function telling you the slope of the original function'. If you are math-phobic, you need to try to get over this and make maths your friend and your horse. You can ride it for miles!

You will also come to notice that I emphasize logic, precise definitions, and careful connected explanations. I *don't* want you to be saying/writing things that could be interpreted in multiple ways, like "the demand will go up".

However, this is not the core *Economics* module (bee2038: Microeconomics II). If you want  a more precise, theoretically complete and mathematically rigorus treatment of this material,  particularly if you are studying Economics and/or want to go to postgraduate study in a related field you probably should switch to that module.

Further suggested maths resources are given below, under (#Other-maths-resources).

<br> \bigskip

*2018: Note to students in Managerial economics who took the BEE1034 'Economics for Management' last term*

I realise that you are facing a special challenge this year because of the changes in this particular prerequisite module, with less 'conventional Economics' covere .

In 2018 I discussed with your student-staff liaison committee chair on how to give you further support. One of the things she suggested was to point you in the direction of the text Edexcel AS/A level Economics. This should be accessible online. I have looked through this book and I agree that it will be helpful both as a prerequisite and to give you a more basic explanation (A-levels) of some of the things that we are covering in this module.

In particular (note these chapters are very short):

*From "theme one: introduction to markets and market failure"*

Chapter one: Economics as a social science

Chapter 3: the economic problem

Chapter 4: production possibility frontiers

Chapter 7: rational decision-making

Chapter 8: Demand (super-important!) but please don't use their somewhat imprecise language "fall/increase in demand/increase in demand)

(Chapters 9 and 10 are essentially re-covered from scratch in our module, going beyond A-level material)

<br> \bigskip


Chapter 11: Supply

Chapter 12: price determination

Chapter 13: the price mechanism
(much of Chapters 14, 15, and 16  cover material overlapping what we are covering, again at a more basic 'A-levels' level; you may find these helpful)

*From 'Theme 3: business behaviour and the labour market'*

Chapter 42: revenue

Chapter 43: Production

chapter 44: Costs (we don't get to all of this in this module)

chapter 45: profit

Chapter 46: market structure (just to get the basic idea)

Chapter 47: perfect competition

Chapter 50: monopoly (we re-cover much of this and go a bit further)

(Much of these chapters in theme 3, as well as chapter 54, overlaps what we are covering, but at the A-level)




I also highly recommend the microeconomics material from the Khan Academy; I will also give you an outline of which sections are most relevant there.

Of course I am also very accessible if you have any questions or need clarification, or just want to talk about some of the material you are struggling with. As I always say, you should feel free to come by my office hours or to make a special appointment outside of these hours I think students who have come to my office hours will definitely agree that they have found been helpful and not stressful. I also encourage you to ask specific questions on the ELE student forum which I will answer carefully. You can also ask questions directly on any of the dropbox hosted files if you get a free dropbox account, and I will try to respond to all of these.




<!---
See older  version of handout for discusion of prerequisites
-->

## Outline and description


**Planned syllabus, coverage:**



*The planned module outline is below;  as noted, timings may need to be adjusted,  and so material may cut for time constraints.  Feel free to skip over the first time you read these notes; you may want to refer to this later.*

- **Module outline, background, Economic models (and maths tools), 'empirical' evidence** (\*) [1a]
    - Nicholson \& Snyder: Chapter 1 and 1a
    - T1:01a (Term 1, week 1, first hour; 'empirical')

- `r format_with_col("First problem set: Mathematical approaches, economic models, revision and warm-up; (to add: some practice MCQ's)","blue")`

Note: I will not go over  all of the fundamental math tools in lecture: please read this section and learn and practice these on your own.

I will put up slides and other resources to help you with this (and we will re-cover some of this when we apply it throughout the module).


- **[Utility and choice](util-choice)** (Utility, preferences, indifference curves, budget constraints ...) [1b-2]
    - NS: Ch 2
    - **T1:01b, 2**
    - `r format_with_col("Second problem set (NS chapter 2): Preferences, Utility, Consumer optimization (individual and market demand curves), and MCQ's for revision","blue")`

[comment]: <> (2024BB)
Optional interesting reading:

- Waldfogel, Joel. "The deadweight loss of Christmas." The American Economic Review 83.5 (1993): 1328-1336.
- Reinstein, David. "The Economics of the Gift." (2014).

[comment]: <> (2024EE)

***

-  **Demand curves** (individual and market, and properties of each) (\*) [3-4]
    - NS: Ch 3
    - T1:3-4

    - `r format_with_col("Second problem set, second part (NS chapter 2-3): Preferences, Utility, Consumer optimization, individual and market demand curves","blue")`


- **Production functions and costs** (brief) [5a]
    - NS: Ch 6 (parts)
    - T1:5a




- **Profit maximisation and supply** (Firms, MR=MC, shut-down) (\*) [5b]
    - NS: Ch 8
    - T1:5a (continued)


- **Perfect competition in a single market** (Brief: Supply curve, entry/exit, CS and PS, tax incidence)  (\*) [5b-6]
    - NS: Ch 9
    - T1:05b-6a

- ** General equilibrium and welfare (brief)** (interrelated markets and equilibrium prices, efficiency of perfect competition, failures) [6a]

- `r format_with_col("Third problem set: Costs/production, perfect competition in a single market, Welfare/General Equilibrium ","blue")`


***



<!--
 **WILL SKIP: Market failures: Asymmetric information** (Moral hazard, adverse selection, signaling)
-->


- **Market failures: Public goods** (attributes, equilibrium underprovision, remedies) [6b-7a]
    - NS: Ch 16 -- public goods section only, possible supplements on voluntary provision of PG/charity
    - T1:06b-7a
    - `r format_with_col("Fourth problem set: Public goods ","blue")`

- Possible supplementary reading:

[comment]: <> (2024BB)
Each reading is optional, but to do well on the exam you need to do at least some of these readings. Note that some of the material below is on the advanced side; try to glean what you can, and stretch your mental muscles.

[comment]: <> (2024EE)

Chaudhuri, 2009. Sustaining cooperation in laboratory public goods experiments: a selective survey of the literature



- **Monopolies, pricing and price discrimination** (single firm with market power; leads to another market failure) [7b-8a]
    - NS: 11.2-11.4
    - T1:07b-8a
    - Article: [Should we help companies tailor prices to your wage packet?](https://theconversation.com/should-we-help-companies-tailor-prices-to-your-wage-packet-47719)
    - With accompanying [worked examples](https://docs.google.com/document/d/16jos_PT9w1wGpyD5A8ZiWJ9HW6kaLOJH6EWc_AYWnkk/pub)
    - More advanced: 'The Government May Want to Encourage Price Discrimination by Income' [Linked here](https://davidreinstein.wordpress.com/research-and-publications/)

- `r format_with_col("Fifth problem set: Monopolies and price discrimination","blue")`



***

-  **Uncertainty** (basic concepts, EU, risk aversion, investment choices) [8b,9a]
    - NS: Ch 4 (not including 4a)
    - T1:08b-9a

    - `r format_with_col("Sixth problem set: Uncertainty (Chapter 4)","blue")`

- Supplementary reading:


- For a popular audience: Reinstein (2016) 'Should you hedge your bets on a Brexit?' [LINK](https://davidreinstein.wordpress.com/2016/06/19/should-you-hedge-your-bets-on-a-brexit/)

- **Game theory (and lab experiments)** (*Strategic* interaction) [9b,10]
    - NS: Ch 5 (parts), plus supplement on experiments
    - T1:09b-10

-  `r format_with_col("Seventh problem set: Game theory (chapter 5, plus a few additional concepts covered in lecture)","blue")`



- **Behavioural economics** -- first lecture (limits to cognition, willpower, self-interest), second lecture (applications) [11]
    - NS: Ch 17, plus supplements
    - T1:11
    - Further readings tbd
    - `r format_with_col("Eighth problem set: Behavioural economics","blue")`

[comment]: <> (2024BB)

Overall each reading is optional, but to do well on the exam you probably need to do at least some of these readings. Note that some of the material below is on the advanced side; try to glean what you can, and stretch your mental muscles.

[comment]: <> (2024EE)

- Supplementary reading: theory
    - Amos Tversky & Daniel Kahneman, 1979. "Prospect Theory: An Analysis of Decision under Risk" (*Seminal*)

- Supplementary reading: applications and empirical work
    - DellaVigna, Stefano. "Psychology and economics: Evidence from the field." Journal of Economic literature 47.2 (2009): 315-372.
    - Benartzi, S. & Thaler, R.H., 2007. Heuristics and biases in retirement savings behavior. The journal of economic perspectives, pp.81-104.
    - Farber, H., 2008. Reference-dependent preferences and labor supply: The case of New York City taxi drivers. The American Economic Review. Available at: http://www.ingentaconnect.com/content/aea/aer/2008/00000098/00000003/art00021 [Accessed November 19, 2015].
    - (Behavioural insights team) EAST: Four simple ways to apply behavioural insight
    - Kellner, Reinstein and Riener, 2016. [Conditional generosity and uncertain income: Field and lab evidence](https://dl.dropboxusercontent.com/u/91553/Giving_and_Probability.pdf)
    - Material linked at giveifyouwin.org

***

- **Revision lecture, catch-up**
    - T1:12a

***


*From the handbook,  here is the official outline of the module:*

> Narrative: The module is also designed to equip students with the key microeconomic principles necessary for the analysis of a range of basic economic problems and policies. It seeks, in particular, to increase the students' abilities to, independently, pose and solve economic questions, especially those relating to policy issues. It emphasises the fundamental conceptual foundations in microeconomics and provides concrete examples of their applications.


 **Some additional resources:**

From the Economics Network: <http://www.economicsnetwork.ac.uk/teaching/Lecture%20Slides/-Intermediate%20Microeconomics>

- Khan academy Microeconomics tutorials
<https://www.khanacademy.org/economics-finance-domain/microeconomics> (all sections are relevant!)

- see also the Khan academy maths tutorials

- Microeconomics for public policy Marcos Vera-Hernandez, University College London



